// Picky-eater friendly recipe library. Every recipe is mild, kid-tested in style, and has "picky tricks".
export const CUISINES = [
  { id: 'canadian', name: 'Canadian', flag: '🇨🇦' },
  { id: 'american', name: 'American', flag: '🇺🇸' },
  { id: 'thai', name: 'Thai', flag: '🇹🇭' },
  { id: 'chinese', name: 'Chinese', flag: '🇨🇳' },
  { id: 'japanese', name: 'Japanese', flag: '🇯🇵' },
  { id: 'italian', name: 'Italian', flag: '🇮🇹' },
  { id: 'mexican', name: 'Mexican', flag: '🇲🇽' },
];

export const MEAL_TYPES = ['Breakfast', 'Lunch', 'Dinner', 'Snack'];

export const RECIPES = [
  // ---------------- CANADIAN ----------------
  { id: 'ca-mac', name: "Stovetop Cheddar Mac & Cheese", cuisine: 'canadian', meal: 'Dinner', emoji: '🧀', time: 20, level: 'Easy', serves: 4,
    tags: ['comfort', 'one-pot', 'no visible veg'],
    ingredients: ["350 g elbow macaroni", "3 tbsp butter", "3 tbsp flour", "2½ cups milk", "2½ cups shredded old cheddar", "½ tsp salt", "Pinch of mustard powder (optional)"],
    steps: ["Boil pasta in salted water 1 minute less than the package says; drain.", "In the same pot melt butter, whisk in flour and cook 1 minute.", "Slowly whisk in milk; simmer, stirring, until it coats a spoon (3–4 min).", "Turn heat off, stir in cheddar a handful at a time until smooth.", "Stir pasta back in and season with salt."],
    picky: ["Use mild cheddar if old cheddar is 'too strong'.", "Blend ½ cup cooked butternut squash into the sauce — the colour hides it.", "Serve plain first; let them add a spoon of peas themselves if they want."],
    grownUp: "Top adult bowls with crispy bacon, black pepper and a spoon of hot sauce." },
  { id: 'ca-poutine', name: "Oven Fry Poutine", cuisine: 'canadian', meal: 'Dinner', emoji: '🍟', time: 40, level: 'Easy', serves: 4,
    tags: ['treat', 'finger food'],
    ingredients: ["4 russet potatoes, cut into fries", "2 tbsp oil", "1 tsp salt", "2 cups cheese curds (or mozzarella chunks)", "2 tbsp butter", "2 tbsp flour", "2 cups beef or chicken broth", "1 tsp ketchup", "1 tsp soy sauce"],
    steps: ["Heat oven to 450°F (230°C). Toss fries with oil and salt, spread on a lined sheet.", "Bake 30–35 min, flipping halfway, until golden.", "Gravy: melt butter, whisk in flour 1 minute, whisk in broth, ketchup and soy; simmer until thick.", "Pile fries in bowls, scatter curds, pour hot gravy over."],
    picky: ["Serve gravy on the side as a dip — no soggy fries.", "Swap curds for shredded mozzarella if the 'squeak' is weird to them.", "Add a side of baby carrots 'for dipping in gravy too'."],
    grownUp: "Add pulled pork or smoked meat and a crack of pepper." },
  { id: 'ca-salmon', name: "Maple-Glazed Salmon Bites", cuisine: 'canadian', meal: 'Dinner', emoji: '🍁', time: 20, level: 'Easy', serves: 4,
    tags: ['sweet', 'quick', 'high protein'],
    ingredients: ["600 g skinless salmon, cut in 1-inch cubes", "3 tbsp maple syrup", "1 tbsp soy sauce", "1 tsp garlic powder", "1 tbsp oil", "Cooked rice to serve"],
    steps: ["Heat oven to 400°F (200°C) and line a sheet pan.", "Whisk maple syrup, soy and garlic powder.", "Toss salmon with oil and half the glaze; spread out.", "Bake 8–10 min, brush with remaining glaze, broil 1–2 min until sticky."],
    picky: ["Call them 'maple candy fish' — the glaze wins kids over.", "Serve on toothpicks for a fun finger food.", "Swap in chicken breast cubes (bake 15 min, to 165°F/74°C) for fish skeptics."],
    grownUp: "Add chili flakes and sesame seeds to the glaze." },
  { id: 'ca-pancakes', name: "Fluffy Maple Pancakes", cuisine: 'canadian', meal: 'Breakfast', emoji: '🥞', time: 20, level: 'Easy', serves: 4,
    tags: ['weekend', 'freezer friendly'],
    ingredients: ["1½ cups flour", "1 tbsp sugar", "3½ tsp baking powder", "½ tsp salt", "1¼ cups milk", "1 egg", "3 tbsp melted butter", "Maple syrup to serve"],
    steps: ["Whisk dry ingredients in a bowl.", "Whisk milk, egg and butter, then stir into dry just until combined (lumps are OK).", "Cook ¼-cup scoops on a buttered pan over medium until bubbles pop, flip, cook 1 min more."],
    picky: ["Make 'dot pancakes' or initials with a squeeze bottle.", "Stir in mashed banana — it tastes like dessert.", "Freeze extras; toast straight from frozen on school mornings."],
    grownUp: "Serve with Greek yogurt, berries and back bacon." },
  { id: 'ca-shepherd', name: "Pâté Chinois (Quebec Shepherd's Pie)", cuisine: 'canadian', meal: 'Dinner', emoji: '🥧', time: 50, level: 'Medium', serves: 6,
    tags: ['make-ahead', 'layers', 'comfort'],
    ingredients: ["500 g lean ground beef", "1 small onion, finely grated", "1 tsp salt", "1 can (398 ml) cream-style corn", "1 cup frozen corn", "5 potatoes, peeled and cubed", "½ cup milk", "3 tbsp butter", "Paprika"],
    steps: ["Boil potatoes until tender, mash with milk, butter and salt.", "Brown beef with the grated onion; season.", "Heat oven to 375°F (190°C). Layer beef in a baking dish, then both corns, then mashed potatoes.", "Dust with paprika and bake 25–30 min until the top is golden."],
    picky: ["Grating the onion makes it disappear into the meat.", "Kids can 'draw' fork patterns on the potato top before baking.", "Scoop layers separately for kids who hate foods touching."],
    grownUp: "Add a splash of Worcestershire to the beef and serve with pickled beets." },
  { id: 'ca-bites', name: "Maple Oat Energy Bites (Nut-Free)", cuisine: 'canadian', meal: 'Snack', emoji: '🍪', time: 10, level: 'Easy', serves: 18,
    tags: ['no-bake', 'lunchbox', 'nut-free'],
    ingredients: ["1 cup quick oats", "½ cup sunflower seed butter (school-safe)", "¼ cup maple syrup", "⅓ cup mini chocolate chips", "2 tbsp ground flax (optional)", "½ tsp vanilla"],
    steps: ["Stir everything together in a bowl.", "Chill 15 minutes so it's easier to roll.", "Roll into tablespoon balls and keep in the fridge up to a week."],
    picky: ["Let kids roll their own and pick sprinkles or coconut to coat them.", "Flax is invisible once mixed — easy fibre boost."],
    grownUp: "Add chopped dried cherries and a pinch of sea salt." },

  // ---------------- AMERICAN ----------------
  { id: 'us-tenders', name: "Crispy Baked Chicken Tenders", cuisine: 'american', meal: 'Dinner', emoji: '🍗', time: 30, level: 'Easy', serves: 4,
    tags: ['finger food', 'dippable', 'freezer friendly'],
    ingredients: ["600 g chicken breast, sliced into strips", "1 cup panko crumbs", "½ cup grated parmesan", "1 tsp garlic powder", "1 tsp paprika", "2 eggs, beaten", "Oil spray", "Honey-mustard or ketchup to dip"],
    steps: ["Heat oven to 425°F (220°C). Put a rack on a sheet pan and spray it.", "Mix panko, parmesan and spices. Dip chicken in egg, then press into crumbs.", "Spray tops with oil; bake 15–18 min until golden and 165°F (74°C) inside."],
    picky: ["A 'dip flight' (ketchup, ranch, honey) makes dinner a game.", "Crush plain corn flakes into the crumbs for extra crunch.", "Serve with the same veggie every time until it becomes 'normal'."],
    grownUp: "Toss adult tenders in Buffalo sauce with blue cheese dip." },
  { id: 'us-sloppy', name: "Hidden-Veggie Sloppy Joes", cuisine: 'american', meal: 'Dinner', emoji: '🍔', time: 25, level: 'Easy', serves: 6,
    tags: ['hidden veg', 'one-pan'],
    ingredients: ["500 g lean ground beef or turkey", "1 carrot and ½ red pepper, very finely grated", "¾ cup ketchup", "¼ cup tomato sauce", "1 tbsp brown sugar", "1 tsp Worcestershire", "1 tsp mustard", "6 soft burger buns"],
    steps: ["Brown the meat, breaking it up small.", "Add the grated veg and cook 3 minutes until soft.", "Stir in ketchup, tomato sauce, sugar, Worcestershire and mustard; simmer 10 minutes.", "Spoon onto toasted buns."],
    picky: ["Grated veg melts right into the sauce — nobody sees it.", "Serve open-faced with a fork for kids who hate messy hands.", "Leftovers make great 'sloppy joe quesadillas'."],
    grownUp: "Top with pickled jalapeños and sharp cheddar." },
  { id: 'us-meatloaf', name: "Mini Meatloaf Muffins", cuisine: 'american', meal: 'Dinner', emoji: '🧁', time: 35, level: 'Easy', serves: 6,
    tags: ['portion-sized', 'make-ahead', 'lunchbox'],
    ingredients: ["700 g lean ground beef", "1 egg", "½ cup breadcrumbs", "¼ cup milk", "½ small onion, grated", "1 tsp salt", "½ cup ketchup + 1 tbsp brown sugar for the glaze"],
    steps: ["Heat oven to 375°F (190°C) and grease a 12-cup muffin tin.", "Mix beef, egg, crumbs, milk, onion and salt gently with your hands.", "Pack into cups, spread ketchup glaze on top.", "Bake 20–22 min until 160°F (71°C) inside."],
    picky: ["Top with a swirl of mashed potato 'frosting' to make meatloaf cupcakes.", "Small size = less intimidating than a slab of meatloaf."],
    grownUp: "Add chopped fresh herbs and a sriracha-ketchup glaze." },
  { id: 'us-grilledcheese', name: "Grilled Cheese & Tomato Soup Dippers", cuisine: 'american', meal: 'Lunch', emoji: '🥪', time: 20, level: 'Easy', serves: 4,
    tags: ['dippable', 'rainy day'],
    ingredients: ["8 slices bread", "Butter", "8 slices cheddar or mozzarella", "1 can (796 ml) crushed tomatoes", "1 cup chicken or veg broth", "½ cup milk or cream", "1 tsp sugar", "Salt"],
    steps: ["Simmer tomatoes, broth and sugar 10 minutes, then blend smooth and stir in milk; season.", "Butter the outside of the bread, add cheese, and cook in a pan over medium 2–3 min per side.", "Cut sandwiches into strips for dunking."],
    picky: ["Cut sandwiches with cookie cutters.", "Blend a roasted carrot into the soup for sweetness.", "Serve the soup in a mug so it feels like a drink."],
    grownUp: "Add caramelized onions and gruyère to adult sandwiches." },
  { id: 'us-frenchtoast', name: "French Toast Sticks", cuisine: 'american', meal: 'Breakfast', emoji: '🍞', time: 15, level: 'Easy', serves: 4,
    tags: ['dippable', 'freezer friendly'],
    ingredients: ["6 slices thick bread, cut in 3 strips each", "3 eggs", "¾ cup milk", "1 tsp cinnamon", "1 tsp vanilla", "Butter for the pan", "Maple syrup to dip"],
    steps: ["Whisk eggs, milk, cinnamon and vanilla in a shallow dish.", "Dip each stick quickly (don't soak).", "Cook in a buttered pan over medium until golden on all sides, about 4 min total."],
    picky: ["Serve syrup in a tiny cup for dipping — kids love control.", "Roll warm sticks in cinnamon sugar for a 'churro' version."],
    grownUp: "Serve with berries, whipped ricotta and crispy bacon." },
  { id: 'us-bbq', name: "Slow-Cooker BBQ Pulled Chicken Sliders", cuisine: 'american', meal: 'Dinner', emoji: '🥪', time: 15, cook: '3–6 hr slow cooker', level: 'Easy', serves: 8,
    tags: ['slow cooker', 'busy night', 'game day'],
    ingredients: ["900 g boneless chicken thighs", "1 cup mild BBQ sauce", "¼ cup apple juice", "1 tbsp brown sugar", "1 tsp garlic powder", "Slider buns", "Coleslaw (optional)"],
    steps: ["Put chicken in the slow cooker; mix BBQ sauce, juice, sugar and garlic and pour over.", "Cook on LOW 6 hours or HIGH 3 hours.", "Shred with two forks right in the sauce.", "Pile on buns."],
    picky: ["Perfect for practice nights — start it in the morning.", "Keep some chicken sauce-free for the 'plain please' kid.", "Serve with cheese slices kids can add themselves."],
    grownUp: "Top with slaw, pickles and hot BBQ sauce." },

  // ---------------- THAI ----------------
  { id: 'th-satay', name: "Mild Chicken Satay with Dipping Sauce", cuisine: 'thai', meal: 'Dinner', emoji: '🍢', time: 30, level: 'Easy', serves: 4,
    tags: ['on a stick', 'dippable', 'mild'],
    ingredients: ["600 g chicken thighs, in strips", "½ cup coconut milk", "1 tbsp soy sauce", "1 tbsp brown sugar", "1 tsp mild curry powder", "Sauce: ⅓ cup peanut or sunflower butter, ⅓ cup coconut milk, 1 tbsp soy, 1 tbsp honey, squeeze of lime"],
    steps: ["Marinate chicken in coconut milk, soy, sugar and curry powder for 15 min (or all day).", "Thread onto skewers (soak wooden ones 10 min).", "Grill or broil 4–5 min per side until 165°F (74°C).", "Warm sauce ingredients together, thin with water until dippable."],
    picky: ["Anything on a stick gets eaten — snip pointy ends for little ones.", "Use sunflower butter to keep it nut-free.", "Serve with plain rice and cucumber coins."],
    grownUp: "Add sriracha and chopped peanuts to the sauce, plus a quick cucumber-chili relish." },
  { id: 'th-padseeew', name: "Pad See Ew (Sweet Soy Noodles)", cuisine: 'thai', meal: 'Dinner', emoji: '🍜', time: 25, level: 'Medium', serves: 4,
    tags: ['noodles', 'sweet-savoury', 'no heat'],
    ingredients: ["400 g wide rice noodles", "300 g chicken, thinly sliced", "2 eggs", "2 cups broccoli florets (small)", "2 tbsp oil", "Sauce: 2 tbsp dark soy (or kecap manis), 1 tbsp soy, 1 tbsp oyster sauce, 1 tbsp brown sugar"],
    steps: ["Soak or cook noodles per package; drain and toss with a little oil.", "Mix the sauce.", "Stir-fry chicken in hot oil until cooked; push aside, scramble the eggs.", "Add broccoli and 2 tbsp water, cover 2 min, then add noodles and sauce; toss until caramelized."],
    picky: ["Sweet dark soy tastes like 'noodle candy' — no spice at all.", "Cut broccoli tiny so it hides in noodles, or leave out and serve on the side."],
    grownUp: "Finish with chili vinegar or chili flakes and a squeeze of lime." },
  { id: 'th-pineapple', name: "Pineapple Fried Rice", cuisine: 'thai', meal: 'Dinner', emoji: '🍍', time: 20, level: 'Easy', serves: 4,
    tags: ['leftover rice', 'sweet', 'one-pan'],
    ingredients: ["4 cups cold cooked jasmine rice", "1 cup pineapple chunks", "2 eggs", "1 cup cooked ham or chicken, diced", "½ cup frozen peas and carrots", "2 tbsp soy sauce", "1 tsp sugar", "1 tsp mild curry powder (optional)"],
    steps: ["Scramble eggs in an oiled wok, remove.", "Stir-fry ham and peas/carrots 2 min.", "Add rice, break up clumps, stir-fry until hot and a little crispy.", "Add pineapple, soy, sugar, curry powder and eggs; toss 1 minute."],
    picky: ["Serve in a hollowed pineapple half — instant 'restaurant' dinner.", "Pineapple sweetness wins over rice skeptics."],
    grownUp: "Add cashews, green onion and a spoon of chili crisp." },
  { id: 'th-curry', name: "Mild Coconut Yellow Curry", cuisine: 'thai', meal: 'Dinner', emoji: '🍛', time: 30, level: 'Easy', serves: 4,
    tags: ['creamy', 'mild', 'one-pot'],
    ingredients: ["500 g chicken, bite-sized", "1 can (400 ml) coconut milk", "1 tbsp mild yellow curry paste (or 2 tsp curry powder)", "2 potatoes, small cubes", "1 carrot, sliced", "1 tbsp fish sauce or soy", "1 tbsp brown sugar", "Jasmine rice"],
    steps: ["Simmer 3 tbsp of the coconut cream with curry paste 1 minute.", "Add chicken, stir to coat.", "Add remaining coconut milk, potatoes, carrot and ½ cup water; simmer 15–18 min until tender.", "Season with fish sauce and sugar; serve over rice."],
    picky: ["Start with just 1 tsp paste — you can add more to adult bowls.", "Potatoes make it familiar, like a creamy stew.", "Serve sauce on the side for 'no sauce' kids."],
    grownUp: "Stir red curry paste and Thai basil into adult portions." },
  { id: 'th-larb', name: "Chicken Lettuce Cups (Mild Larb)", cuisine: 'thai', meal: 'Lunch', emoji: '🥬', time: 20, level: 'Easy', serves: 4,
    tags: ['build-your-own', 'fresh', 'light'],
    ingredients: ["500 g ground chicken", "1 tbsp oil", "2 tbsp fish sauce or soy", "1 tbsp lime juice", "1 tbsp brown sugar", "Butter lettuce leaves", "Cucumber, carrot matchsticks, cooked rice"],
    steps: ["Cook chicken in oil, breaking it up, until no pink remains.", "Stir in fish sauce, lime juice and sugar.", "Set out lettuce, rice and veg; everyone builds their own cups."],
    picky: ["Build-your-own means kids choose what goes in.", "Rice-in-a-lettuce-taco is a great first step."],
    grownUp: "Add toasted rice powder, mint, shallots and chili flakes." },
  { id: 'th-mango', name: "Mango Sticky Rice", cuisine: 'thai', meal: 'Snack', emoji: '🥭', time: 35, cook: '1 hr soak', level: 'Medium', serves: 4,
    tags: ['dessert', 'weekend treat'],
    ingredients: ["1 cup glutinous (sticky) rice, soaked 1+ hour", "1 can (400 ml) coconut milk", "⅓ cup sugar", "½ tsp salt", "2 ripe mangoes, sliced"],
    steps: ["Steam soaked rice 20–25 min until tender and chewy.", "Warm ¾ of the coconut milk with sugar and salt; pour over hot rice and let it soak in 15 min.", "Simmer the rest of the coconut milk with a pinch of salt until slightly thick for drizzling.", "Serve rice with mango and the drizzle."],
    picky: ["It's dessert with fruit — an easy win.", "Use regular jasmine rice cooked in coconut milk if you can't find sticky rice."],
    grownUp: "Sprinkle toasted sesame seeds and a little lime zest." },

  // ---------------- CHINESE ----------------
  { id: 'cn-honeygarlic', name: "Honey Garlic Chicken", cuisine: 'chinese', meal: 'Dinner', emoji: '🍯', time: 25, level: 'Easy', serves: 4,
    tags: ['sticky', 'sweet', 'kid favourite'],
    ingredients: ["600 g chicken thighs, bite-sized", "3 tbsp cornstarch", "2 tbsp oil", "⅓ cup honey", "3 tbsp soy sauce", "2 cloves garlic, grated", "1 tbsp ketchup", "Rice to serve"],
    steps: ["Toss chicken in cornstarch.", "Pan-fry in oil over medium-high until golden and cooked through (8–10 min).", "Stir honey, soy, garlic and ketchup together; pour in and bubble 1–2 min until sticky."],
    picky: ["Grated garlic melts into the sauce — no chunks.", "Serve with steamed broccoli 'trees' to dip in the extra sauce."],
    grownUp: "Add chili flakes and toasted sesame seeds." },
  { id: 'cn-friedrice', name: "Classic Egg Fried Rice", cuisine: 'chinese', meal: 'Dinner', emoji: '🍚', time: 15, level: 'Easy', serves: 4,
    tags: ['leftover rice', 'quick', 'budget'],
    ingredients: ["4 cups cold cooked rice", "3 eggs", "2 tbsp oil", "¾ cup frozen peas and carrots", "2 green onions (optional)", "2 tbsp soy sauce", "1 tsp sesame oil"],
    steps: ["Scramble eggs in hot oil, break into small bits, remove.", "Stir-fry peas and carrots 2 min.", "Add rice and fry, pressing and tossing, until hot and slightly crispy.", "Add soy, sesame oil and egg; toss."],
    picky: ["'Rainbow rice' — let kids count the colours.", "Leave veg out of one portion and add ham or corn instead."],
    grownUp: "Top with a fried egg and chili oil." },
  { id: 'cn-lomein', name: "Chicken Lo Mein", cuisine: 'chinese', meal: 'Dinner', emoji: '🍜', time: 25, level: 'Easy', serves: 4,
    tags: ['noodles', 'takeout at home'],
    ingredients: ["350 g lo mein or spaghetti", "300 g chicken, thin strips", "1 cup snap peas or shredded cabbage", "1 carrot, matchsticks", "Sauce: 3 tbsp soy, 1 tbsp oyster sauce, 1 tbsp honey, 1 tsp sesame oil, 2 tbsp water"],
    steps: ["Cook noodles, drain and rinse briefly.", "Stir-fry chicken until cooked; add veg for 2 minutes.", "Add noodles and sauce; toss until glossy and hot."],
    picky: ["Spaghetti works perfectly — it looks familiar.", "Twirl it on chopsticks with a rubber band 'trainer'."],
    grownUp: "Add garlic, ginger and sambal oelek." },
  { id: 'cn-sweetsour', name: "Baked Sweet & Sour Chicken", cuisine: 'chinese', meal: 'Dinner', emoji: '🍗', time: 40, level: 'Medium', serves: 4,
    tags: ['sweet', 'baked not fried'],
    ingredients: ["600 g chicken breast, cubed", "½ cup cornstarch", "2 eggs, beaten", "Sauce: ½ cup sugar, ¼ cup ketchup, ⅓ cup rice vinegar, 1 tbsp soy, 1 tsp garlic powder", "1 cup pineapple chunks", "Rice"],
    steps: ["Heat oven to 325°F (160°C).", "Toss chicken in cornstarch, dip in egg, and sear in an oiled pan just until golden (not cooked through).", "Place in a baking dish, pour sauce over, add pineapple.", "Bake 30 min, stirring halfway, until sticky and 165°F (74°C) inside."],
    picky: ["Tastes like the takeout they love.", "Pineapple 'treasures' make fruit part of dinner."],
    grownUp: "Add peppers and onions and a pinch of chili flakes." },
  { id: 'cn-dumplings', name: "Pork & Cabbage Potstickers", cuisine: 'chinese', meal: 'Dinner', emoji: '🥟', time: 45, level: 'Medium', serves: 4,
    tags: ['family project', 'freezer friendly'],
    ingredients: ["400 g ground pork", "1½ cups finely chopped napa cabbage (salted, squeezed dry)", "2 tbsp soy sauce", "1 tsp sesame oil", "1 tsp grated ginger", "40 round dumpling wrappers", "Dip: soy sauce + a little rice vinegar + honey"],
    steps: ["Mix pork, cabbage, soy, sesame oil and ginger.", "Put 1 tsp filling in each wrapper, wet the edge, fold and pinch shut.", "Fry flat side down in an oiled pan 2 min, add ⅓ cup water, cover and steam 6 min.", "Uncover and fry until the bottoms crisp."],
    picky: ["Kids who fold their own dumplings eat their own dumplings.", "Freeze on a tray, then bag — cook from frozen (add 2 min steam)."],
    grownUp: "Add chili crisp to the dip." },
  { id: 'cn-eggdrop', name: "Egg Drop Soup", cuisine: 'chinese', meal: 'Lunch', emoji: '🥣', time: 10, level: 'Easy', serves: 4,
    tags: ['5 ingredients', 'sick day'],
    ingredients: ["6 cups chicken broth", "2 tbsp cornstarch mixed with 3 tbsp water", "3 eggs, beaten", "½ tsp sesame oil", "Salt and white pepper", "Corn kernels (optional)"],
    steps: ["Bring broth to a simmer, stir in cornstarch slurry until slightly thick.", "Stir the soup in a circle and slowly drizzle in eggs to make ribbons.", "Turn off heat, add sesame oil, season."],
    picky: ["Call it 'cloud soup'.", "Add creamed corn for a sweeter version kids love."],
    grownUp: "Add tofu, green onion and chili oil." },
  { id: 'cn-beefbroc', name: "Beef & Broccoli", cuisine: 'chinese', meal: 'Dinner', emoji: '🥦', time: 20, level: 'Easy', serves: 4,
    tags: ['quick', 'high protein'],
    ingredients: ["500 g flank steak, thinly sliced across the grain", "1 tbsp cornstarch", "3 cups small broccoli florets", "2 tbsp oil", "Sauce: ¼ cup soy, 2 tbsp brown sugar, 1 tbsp oyster sauce, ½ cup broth, 1 tsp cornstarch"],
    steps: ["Toss beef with cornstarch.", "Sear beef in hot oil in batches, remove.", "Add broccoli and 3 tbsp water, cover 2 min.", "Add sauce and beef, simmer until glossy."],
    picky: ["Thin slicing makes the beef tender and less 'chewy'.", "Serve a kid bowl with broccoli on the side, not mixed."],
    grownUp: "Add fresh ginger and garlic and a dash of rice wine." },

  // ---------------- JAPANESE ----------------
  { id: 'jp-teriyaki', name: "Chicken Teriyaki Rice Bowls", cuisine: 'japanese', meal: 'Dinner', emoji: '🍱', time: 25, level: 'Easy', serves: 4,
    tags: ['sticky', 'bowl', 'lunchbox leftovers'],
    ingredients: ["600 g chicken thighs", "Sauce: ¼ cup soy sauce, 2 tbsp mirin (or 1 tbsp sugar), 2 tbsp honey, 1 tsp grated ginger", "1 tsp cornstarch in 1 tbsp water", "Rice, cucumber, edamame, sesame seeds"],
    steps: ["Pan-sear chicken skin-side down (or just thighs) over medium until golden, flip and cook through.", "Add sauce and simmer, turning, until sticky; stir in cornstarch slurry.", "Slice and serve over rice with cucumber and edamame."],
    picky: ["Bowls with separate little piles = no 'touching foods' drama.", "Extra sauce on rice makes it 'candy rice'."],
    grownUp: "Top with pickled ginger, spicy mayo and furikake." },
  { id: 'jp-onigiri', name: "Onigiri Rice Balls", cuisine: 'japanese', meal: 'Lunch', emoji: '🍙', time: 25, level: 'Easy', serves: 6,
    tags: ['lunchbox', 'hands-on', 'finger food'],
    ingredients: ["3 cups cooked Japanese short-grain rice, warm", "Salt", "Fillings: canned tuna + mayo, flaked salmon, or cheese cubes", "Nori sheets, cut in strips", "Furikake (optional)"],
    steps: ["Wet hands and rub with a pinch of salt.", "Flatten a scoop of rice in your palm, add a spoon of filling, close the rice around it.", "Press into a triangle or ball; wrap with a nori strip."],
    picky: ["Let kids pick fillings — even plain buttered rice balls count.", "Add nori 'faces' to make characters."],
    grownUp: "Fill with spicy salmon or umeboshi." },
  { id: 'jp-katsu', name: "Chicken Katsu with Sweet Katsu Sauce", cuisine: 'japanese', meal: 'Dinner', emoji: '🍛', time: 30, level: 'Medium', serves: 4,
    tags: ['crispy', 'dippable'],
    ingredients: ["2 chicken breasts, butterflied and pounded thin", "½ cup flour", "2 eggs", "1½ cups panko", "Oil for pan-frying", "Sauce: ¼ cup ketchup, 2 tbsp Worcestershire, 1 tbsp soy, 1 tbsp sugar", "Rice and shredded cabbage"],
    steps: ["Season chicken; dredge in flour, then egg, then panko.", "Shallow-fry in ½ inch of oil over medium, 3–4 min per side, until golden and 165°F (74°C).", "Stir sauce ingredients together.", "Slice katsu into strips and serve with rice."],
    picky: ["It's basically a big chicken nugget — tell them so.", "Katsu sauce tastes like fancy ketchup."],
    grownUp: "Serve with Japanese curry sauce and Kewpie mayo." },
  { id: 'jp-yakiudon', name: "Yaki Udon Stir-Fry", cuisine: 'japanese', meal: 'Dinner', emoji: '🍜', time: 20, level: 'Easy', serves: 4,
    tags: ['thick noodles', 'quick'],
    ingredients: ["4 packs frozen or vacuum udon", "250 g chicken or pork, thin slices", "2 cups cabbage, shredded", "1 carrot, matchsticks", "Sauce: 3 tbsp soy, 1 tbsp oyster sauce, 1 tbsp mirin or honey, 1 tsp sugar"],
    steps: ["Loosen udon in hot water 1 minute, drain.", "Stir-fry meat until cooked, add veg 2 min.", "Add udon and sauce, toss 2 min until coated."],
    picky: ["Chunky 'worm noodles' are fun to slurp.", "Keep a plain buttered udon bowl for the pickiest."],
    grownUp: "Finish with bonito flakes and shichimi pepper." },
  { id: 'jp-tamago', name: "Tamagoyaki (Sweet Rolled Omelette)", cuisine: 'japanese', meal: 'Breakfast', emoji: '🍳', time: 15, level: 'Medium', serves: 2,
    tags: ['eggs', 'lunchbox'],
    ingredients: ["4 eggs", "1 tbsp sugar", "1 tsp soy sauce", "2 tbsp milk or water", "Oil"],
    steps: ["Whisk eggs, sugar, soy and milk.", "Pour a thin layer into an oiled non-stick pan over medium-low; when almost set, roll it to one side.", "Pour another thin layer, lift the roll so egg flows under, roll back over. Repeat.", "Rest 2 min, slice into rounds."],
    picky: ["Slightly sweet eggs win over 'I don't like eggs' kids.", "Roll a slice of ham or cheese inside."],
    grownUp: "Add dashi and green onion for a savoury version." },
  { id: 'jp-curry', name: "Japanese Curry Rice (Mild)", cuisine: 'japanese', meal: 'Dinner', emoji: '🍛', time: 40, level: 'Easy', serves: 6,
    tags: ['mild', 'one-pot', 'make-ahead'],
    ingredients: ["500 g chicken or beef, bite-sized", "1 onion, sliced", "2 carrots, chunks", "2 potatoes, chunks", "1 box Japanese curry roux, MILD (half box for 4)", "4 cups water", "1 grated apple (optional)", "Rice"],
    steps: ["Brown meat and onion in a pot.", "Add carrots, potatoes and water; simmer 15–20 min until tender.", "Turn off heat, add roux pieces and grated apple; stir until melted.", "Simmer 5 min until thick; serve over rice."],
    picky: ["Mild roux is sweet, not spicy — like a gravy stew.", "Serve the curry beside the rice, not on top, for cautious kids."],
    grownUp: "Use the 'hot' roux or add chili oil and a fried egg." },

  // ---------------- ITALIAN ----------------
  { id: 'it-hiddenveg', name: "Hidden-Veggie Tomato Pasta", cuisine: 'italian', meal: 'Dinner', emoji: '🍝', time: 30, level: 'Easy', serves: 4,
    tags: ['hidden veg', 'batch sauce', 'freezer friendly'],
    ingredients: ["400 g pasta", "1 tbsp olive oil", "1 carrot, 1 small zucchini, ½ red pepper — chopped", "1 can (796 ml) crushed tomatoes", "1 tsp sugar", "1 tsp salt", "½ cup grated parmesan"],
    steps: ["Soften veg in olive oil 8 minutes.", "Add tomatoes, sugar and salt; simmer 15 min.", "Blend completely smooth.", "Toss with cooked pasta and parmesan."],
    picky: ["Smooth sauce = zero visible veg.", "Make a triple batch and freeze in cups."],
    grownUp: "Add garlic, chili flakes and fresh basil." },
  { id: 'it-pizza', name: "Build-Your-Own Pizza Night", cuisine: 'italian', meal: 'Dinner', emoji: '🍕', time: 30, level: 'Easy', serves: 4,
    tags: ['build-your-own', 'family night', 'Friday'],
    ingredients: ["4 naan or small pizza crusts", "¾ cup pizza sauce", "2 cups shredded mozzarella", "Toppings bar: pepperoni, ham, pineapple, peppers, olives, mushrooms"],
    steps: ["Heat oven to 425°F (220°C).", "Everyone spreads sauce and picks toppings.", "Bake on a sheet pan 10–12 min until bubbly and golden."],
    picky: ["Kids who build it, eat it — even if it's just cheese.", "Offer one 'new' topping each week and see who tries it."],
    grownUp: "Hot honey, prosciutto and arugula after baking." },
  { id: 'it-meatballs', name: "Mini Meatballs & Spaghetti", cuisine: 'italian', meal: 'Dinner', emoji: '🍝', time: 40, level: 'Medium', serves: 6,
    tags: ['freezer friendly', 'classic'],
    ingredients: ["500 g lean ground beef (or half pork)", "1 egg", "½ cup breadcrumbs", "¼ cup milk", "¼ cup parmesan", "1 tsp salt", "1 jar (650 ml) marinara", "450 g spaghetti"],
    steps: ["Mix beef, egg, crumbs, milk, parmesan and salt; roll into marble-size balls.", "Bake at 400°F (200°C) 12–14 min.", "Simmer meatballs in marinara 10 min.", "Serve over spaghetti."],
    picky: ["Marble-size meatballs are more fun and less scary.", "Kids can roll the meatballs."],
    grownUp: "Add fennel seed and chili to the mix; top with ricotta." },
  { id: 'it-parm', name: "Baked Chicken Parmesan", cuisine: 'italian', meal: 'Dinner', emoji: '🧀', time: 35, level: 'Easy', serves: 4,
    tags: ['crispy', 'cheesy'],
    ingredients: ["2 chicken breasts, halved into cutlets", "1 egg", "1 cup Italian breadcrumbs", "¼ cup parmesan", "1 cup marinara", "1 cup shredded mozzarella", "Pasta or garlic bread"],
    steps: ["Heat oven to 425°F (220°C).", "Dip cutlets in egg, then crumbs mixed with parmesan; bake on a greased rack 15 min.", "Top each with marinara and mozzarella; bake 5–8 min more until bubbly and 165°F (74°C)."],
    picky: ["Sauce under the cheese, not everywhere, for sauce-averse kids.", "Slice into 'pizza chicken' strips."],
    grownUp: "Serve on a crusty roll with fresh basil and chili flakes." },
  { id: 'it-burro', name: "Pasta al Burro (Butter & Parmesan Pasta)", cuisine: 'italian', meal: 'Lunch', emoji: '🧈', time: 12, level: 'Easy', serves: 4,
    tags: ['ultimate picky', '3 ingredients'],
    ingredients: ["400 g short pasta or spaghetti", "4 tbsp butter", "¾ cup finely grated parmesan", "Salt"],
    steps: ["Cook pasta in well-salted water; save 1 cup pasta water.", "Toss drained pasta with butter and ½ cup pasta water over low heat.", "Add parmesan and toss until creamy, adding more water if needed."],
    picky: ["The 'safe food' for tough days — pair with one fruit they like.", "Stir in peas for the brave ones."],
    grownUp: "Add lemon zest, black pepper and garlic (cacio e pepe style)." },
  { id: 'it-rollups', name: "Lasagna Roll-Ups", cuisine: 'italian', meal: 'Dinner', emoji: '🌯', time: 45, level: 'Medium', serves: 6,
    tags: ['portion-sized', 'make-ahead'],
    ingredients: ["12 lasagna noodles, cooked", "475 g ricotta", "1 cup shredded mozzarella + 1 cup for top", "½ cup parmesan", "1 egg", "1 cup chopped spinach (optional)", "1 jar (650 ml) marinara"],
    steps: ["Heat oven to 375°F (190°C). Spread 1 cup marinara in a baking dish.", "Mix ricotta, 1 cup mozzarella, parmesan, egg and spinach.", "Spread on each noodle and roll up; set seam-side down.", "Top with remaining sauce and mozzarella; cover and bake 25 min, uncover 10 min."],
    picky: ["Individual rolls = everyone gets 'their own lasagna'.", "Blend the spinach into the ricotta so it's just 'green cheese'."],
    grownUp: "Add Italian sausage to the sauce." },

  // ---------------- MEXICAN ----------------
  { id: 'mx-tacos', name: "Build-Your-Own Taco Night", cuisine: 'mexican', meal: 'Dinner', emoji: '🌮', time: 25, level: 'Easy', serves: 4,
    tags: ['build-your-own', 'Tuesday'],
    ingredients: ["500 g ground beef or turkey", "Mild seasoning: 1 tsp cumin, 1 tsp paprika, 1 tsp garlic powder, ½ tsp oregano, ½ tsp salt", "⅓ cup water", "Hard shells and soft tortillas", "Toppings: cheese, lettuce, tomato, sour cream, mild salsa, corn"],
    steps: ["Brown the meat.", "Add seasoning and water; simmer until saucy.", "Warm shells; set out a toppings bar and let everyone build."],
    picky: ["Homemade mild seasoning avoids the hidden spice in packets.", "A 'taco plate' (meat, cheese, chips separately) is still taco night."],
    grownUp: "Pickled onions, cilantro, lime and hot sauce." },
  { id: 'mx-quesadilla', name: "Cheesy Chicken Quesadillas", cuisine: 'mexican', meal: 'Lunch', emoji: '🫓', time: 15, level: 'Easy', serves: 4,
    tags: ['leftover chicken', 'dippable'],
    ingredients: ["8 small flour tortillas", "2 cups shredded cheddar/Monterey Jack", "1½ cups cooked shredded chicken", "½ cup corn or black beans (optional)", "Sour cream and mild salsa to dip"],
    steps: ["Sprinkle cheese, chicken and extras on half of each tortilla; fold.", "Cook in a dry pan over medium 2–3 min per side until golden and melty.", "Cut into triangles."],
    picky: ["Cheese-only quesadillas count — add chicken next time.", "Blend black beans smooth and spread thin inside — invisible."],
    grownUp: "Add jalapeños, chorizo and pickled red onion." },
  { id: 'mx-bowl', name: "Burrito Bowls", cuisine: 'mexican', meal: 'Dinner', emoji: '🥙', time: 30, level: 'Easy', serves: 4,
    tags: ['bowl', 'build-your-own', 'meal prep'],
    ingredients: ["500 g chicken breast", "1 tsp each cumin, paprika, garlic powder; ½ tsp salt", "2 cups rice cooked with a squeeze of lime", "1 can black beans, warmed", "1 cup corn", "Cheese, avocado, sour cream, mild salsa"],
    steps: ["Season chicken and pan-cook 5–6 min per side to 165°F (74°C); rest and slice.", "Set out rice, beans, corn, chicken and toppings.", "Everyone builds a bowl."],
    picky: ["Deconstructed = picky-proof.", "Crushed tortilla chips on top make any bowl exciting."],
    grownUp: "Chipotle crema and fresh pico de gallo." },
  { id: 'mx-enchiladas', name: "Mild Cheesy Chicken Enchiladas", cuisine: 'mexican', meal: 'Dinner', emoji: '🌯', time: 40, level: 'Medium', serves: 6,
    tags: ['make-ahead', 'cheesy'],
    ingredients: ["3 cups cooked shredded chicken", "2½ cups shredded cheese", "½ cup sour cream", "8 flour tortillas", "2 cups mild red enchilada sauce (or tomato sauce + 1 tsp cumin)"],
    steps: ["Heat oven to 375°F (190°C); spread ½ cup sauce in a baking dish.", "Mix chicken, sour cream and 1 cup cheese.", "Fill and roll tortillas; place seam-side down.", "Top with sauce and remaining cheese; bake 20 min."],
    picky: ["Make a couple 'cheese only' rolls on one end of the pan.", "Sour cream in the filling cools any spice."],
    grownUp: "Add green chiles and top with cilantro and hot sauce." },
  { id: 'mx-fajitas', name: "Sheet-Pan Chicken Fajitas", cuisine: 'mexican', meal: 'Dinner', emoji: '🫑', time: 30, level: 'Easy', serves: 4,
    tags: ['one-pan', 'busy night'],
    ingredients: ["600 g chicken breast, strips", "3 bell peppers, strips", "1 onion, sliced", "2 tbsp oil", "Seasoning: 2 tsp paprika, 1 tsp cumin, 1 tsp garlic powder, ½ tsp salt", "Tortillas, cheese, sour cream"],
    steps: ["Heat oven to 425°F (220°C).", "Toss chicken and veg with oil and seasoning on a sheet pan.", "Roast 18–20 min, stirring once.", "Wrap in warm tortillas."],
    picky: ["Keep kid chicken on its own corner of the pan, unseasoned if needed.", "Sweet red/yellow peppers are easier than green."],
    grownUp: "Add chipotle or cayenne to the seasoning." },
  { id: 'mx-breakfast', name: "Breakfast Burritos", cuisine: 'mexican', meal: 'Breakfast', emoji: '🌯', time: 20, level: 'Easy', serves: 6,
    tags: ['freezer friendly', 'grab-and-go'],
    ingredients: ["8 eggs", "¼ cup milk", "1 cup cooked diced potatoes or hash browns", "1 cup cooked sausage or bacon bits", "1½ cups shredded cheese", "6 large flour tortillas"],
    steps: ["Scramble eggs with milk until just set.", "Warm tortillas; fill with eggs, potatoes, meat and cheese.", "Roll tightly; toast seam-side down in a pan 1 min.", "Wrap extras in foil and freeze; reheat 1–2 min in the microwave (unwrapped, in paper towel)."],
    picky: ["Mini burritos in small tortillas for small hands.", "Ketchup is a totally legit burrito sauce."],
    grownUp: "Add salsa verde, avocado and pickled jalapeños." },
  { id: 'mx-crisps', name: "Cinnamon Sugar Tortilla Crisps & Fruit Salsa", cuisine: 'mexican', meal: 'Snack', emoji: '🍓', time: 15, level: 'Easy', serves: 4,
    tags: ['dessert', 'fruit'],
    ingredients: ["4 flour tortillas", "2 tbsp melted butter", "3 tbsp sugar + 1 tsp cinnamon", "Fruit salsa: 1 cup diced strawberries, 1 apple diced, 1 kiwi diced, 1 tbsp honey, squeeze of lime"],
    steps: ["Heat oven to 375°F (190°C).", "Brush tortillas with butter, sprinkle cinnamon sugar, cut into wedges.", "Bake 8–10 min until crisp.", "Stir fruit salsa ingredients together and dip."],
    picky: ["Chips + fruit = the easiest fruit win of the week.", "Let them choose the fruits."],
    grownUp: "Add a pinch of chili-lime seasoning (Tajín) to the fruit." },
];

// Deterministic daily picks: rotate through cuisines so the feed changes every day but is the same on every device.
export function dailyPicks(dateStr, count = 4) {
  const seed = [...dateStr].reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, 7);
  const rand = mulberry(seed);
  const pool = RECIPES.filter(r => r.meal === 'Dinner' || r.meal === 'Lunch');
  const byCuisine = CUISINES.map(c => pool.filter(r => r.cuisine === c.id));
  const start = Math.floor(rand() * CUISINES.length);
  const picks = [];
  for (let i = 0; picks.length < count && i < CUISINES.length * 2; i++) {
    const list = byCuisine[(start + i * 2) % CUISINES.length];
    const r = list[Math.floor(rand() * list.length)];
    if (r && !picks.includes(r)) picks.push(r);
  }
  // one breakfast or snack bonus pick
  const extras = RECIPES.filter(r => r.meal === 'Breakfast' || r.meal === 'Snack');
  picks.push(extras[Math.floor(rand() * extras.length)]);
  return picks;
}

function mulberry(a) {
  return function () {
    a |= 0; a = a + 0x6D2B79F5 | 0;
    let t = Math.imul(a ^ a >>> 15, 1 | a);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
