// Picky-eater friendly recipe library. Every recipe is mild, kid-tested in style, and has "picky tricks".
export const CUISINES = [
  { id: 'canadian', name: 'Canadian', flag: '🇨🇦' },
  { id: 'american', name: 'American', flag: '🇺🇸' },
  { id: 'thai', name: 'Thai', flag: '🇹🇭' },
  { id: 'chinese', name: 'Chinese', flag: '🇨🇳' },
  { id: 'japanese', name: 'Japanese', flag: '🇯🇵' },
  { id: 'italian', name: 'Italian', flag: '🇮🇹' },
  { id: 'mexican', name: 'Mexican', flag: '🇲🇽' },
];

export const MEAL_TYPES = ['Breakfast', 'Lunch', 'Dinner', 'Snack'];

const BASE = [
  // ---------------- CANADIAN ----------------
  { id: 'ca-mac', name: "Stovetop Cheddar Mac & Cheese", cuisine: 'canadian', meal: 'Dinner', emoji: '🧀', time: 20, level: 'Easy', serves: 4,
    tags: ['comfort', 'one-pot', 'no visible veg'],
    ingredients: ["350 g elbow macaroni", "3 tbsp butter", "3 tbsp flour", "2½ cups milk", "2½ cups shredded old cheddar", "½ tsp salt", "Pinch of mustard powder (optional)"],
    steps: ["Boil pasta in salted water 1 minute less than the package says; drain.", "In the same pot melt butter, whisk in flour and cook 1 minute.", "Slowly whisk in milk; simmer, stirring, until it coats a spoon (3–4 min).", "Turn heat off, stir in cheddar a handful at a time until smooth.", "Stir pasta back in and season with salt."],
    picky: ["Use mild cheddar if old cheddar is 'too strong'.", "Blend ½ cup cooked butternut squash into the sauce — the colour hides it.", "Serve plain first; let them add a spoon of peas themselves if they want."],
    grownUp: "Top adult bowls with crispy bacon, black pepper and a spoon of hot sauce." },
  { id: 'ca-poutine', name: "Oven Fry Poutine", cuisine: 'canadian', meal: 'Dinner', emoji: '🍟', time: 40, level: 'Easy', serves: 4,
    tags: ['treat', 'finger food'],
    ingredients: ["4 russet potatoes, cut into fries", "2 tbsp oil", "1 tsp salt", "2 cups cheese curds (or mozzarella chunks)", "2 tbsp butter", "2 tbsp flour", "2 cups beef or chicken broth", "1 tsp ketchup", "1 tsp soy sauce"],
    steps: ["Heat oven to 450°F (230°C). Toss fries with oil and salt, spread on a lined sheet.", "Bake 30–35 min, flipping halfway, until golden.", "Gravy: melt butter, whisk in flour 1 minute, whisk in broth, ketchup and soy; simmer until thick.", "Pile fries in bowls, scatter curds, pour hot gravy over."],
    picky: ["Serve gravy on the side as a dip — no soggy fries.", "Swap curds for shredded mozzarella if the 'squeak' is weird to them.", "Add a side of baby carrots 'for dipping in gravy too'."],
    grownUp: "Add pulled pork or smoked meat and a crack of pepper." },
  { id: 'ca-salmon', name: "Maple-Glazed Salmon Bites", cuisine: 'canadian', meal: 'Dinner', emoji: '🍁', time: 20, level: 'Easy', serves: 4,
    tags: ['sweet', 'quick', 'high protein'],
    ingredients: ["600 g skinless salmon, cut in 1-inch cubes", "3 tbsp maple syrup", "1 tbsp soy sauce", "1 tsp garlic powder", "1 tbsp oil", "Cooked rice to serve"],
    steps: ["Heat oven to 400°F (200°C) and line a sheet pan.", "Whisk maple syrup, soy and garlic powder.", "Toss salmon with oil and half the glaze; spread out.", "Bake 8–10 min, brush with remaining glaze, broil 1–2 min until sticky."],
    picky: ["Call them 'maple candy fish' — the glaze wins kids over.", "Serve on toothpicks for a fun finger food.", "Swap in chicken breast cubes (bake 15 min, to 165°F/74°C) for fish skeptics."],
    grownUp: "Add chili flakes and sesame seeds to the glaze." },
  { id: 'ca-pancakes', name: "Fluffy Maple Pancakes", cuisine: 'canadian', meal: 'Breakfast', emoji: '🥞', time: 20, level: 'Easy', serves: 4,
    tags: ['weekend', 'freezer friendly'],
    ingredients: ["1½ cups flour", "1 tbsp sugar", "3½ tsp baking powder", "½ tsp salt", "1¼ cups milk", "1 egg", "3 tbsp melted butter", "Maple syrup to serve"],
    steps: ["Whisk dry ingredients in a bowl.", "Whisk milk, egg and butter, then stir into dry just until combined (lumps are OK).", "Cook ¼-cup scoops on a buttered pan over medium until bubbles pop, flip, cook 1 min more."],
    picky: ["Make 'dot pancakes' or initials with a squeeze bottle.", "Stir in mashed banana — it tastes like dessert.", "Freeze extras; toast straight from frozen on school mornings."],
    grownUp: "Serve with Greek yogurt, berries and back bacon." },
  { id: 'ca-shepherd', name: "Pâté Chinois (Quebec Shepherd's Pie)", cuisine: 'canadian', meal: 'Dinner', emoji: '🥧', time: 50, level: 'Medium', serves: 6,
    tags: ['make-ahead', 'layers', 'comfort'],
    ingredients: ["500 g lean ground beef", "1 small onion, finely grated", "1 tsp salt", "1 can (398 ml) cream-style corn", "1 cup frozen corn", "5 potatoes, peeled and cubed", "½ cup milk", "3 tbsp butter", "Paprika"],
    steps: ["Boil potatoes until tender, mash with milk, butter and salt.", "Brown beef with the grated onion; season.", "Heat oven to 375°F (190°C). Layer beef in a baking dish, then both corns, then mashed potatoes.", "Dust with paprika and bake 25–30 min until the top is golden."],
    picky: ["Grating the onion makes it disappear into the meat.", "Kids can 'draw' fork patterns on the potato top before baking.", "Scoop layers separately for kids who hate foods touching."],
    grownUp: "Add a splash of Worcestershire to the beef and serve with pickled beets." },
  { id: 'ca-bites', name: "Maple Oat Energy Bites (Nut-Free)", cuisine: 'canadian', meal: 'Snack', emoji: '🍪', time: 10, level: 'Easy', serves: 18,
    tags: ['no-bake', 'lunchbox', 'nut-free'],
    ingredients: ["1 cup quick oats", "½ cup sunflower seed butter (school-safe)", "¼ cup maple syrup", "⅓ cup mini chocolate chips", "2 tbsp ground flax (optional)", "½ tsp vanilla"],
    steps: ["Stir everything together in a bowl.", "Chill 15 minutes so it's easier to roll.", "Roll into tablespoon balls and keep in the fridge up to a week."],
    picky: ["Let kids roll their own and pick sprinkles or coconut to coat them.", "Flax is invisible once mixed — easy fibre boost."],
    grownUp: "Add chopped dried cherries and a pinch of sea salt." },

  // ---------------- AMERICAN ----------------
  { id: 'us-tenders', name: "Crispy Baked Chicken Tenders", cuisine: 'american', meal: 'Dinner', emoji: '🍗', time: 30, level: 'Easy', serves: 4,
    tags: ['finger food', 'dippable', 'freezer friendly'],
    ingredients: ["600 g chicken breast, sliced into strips", "1 cup panko crumbs", "½ cup grated parmesan", "1 tsp garlic powder", "1 tsp paprika", "2 eggs, beaten", "Oil spray", "Honey-mustard or ketchup to dip"],
    steps: ["Heat oven to 425°F (220°C). Put a rack on a sheet pan and spray it.", "Mix panko, parmesan and spices. Dip chicken in egg, then press into crumbs.", "Spray tops with oil; bake 15–18 min until golden and 165°F (74°C) inside."],
    picky: ["A 'dip flight' (ketchup, ranch, honey) makes dinner a game.", "Crush plain corn flakes into the crumbs for extra crunch.", "Serve with the same veggie every time until it becomes 'normal'."],
    grownUp: "Toss adult tenders in Buffalo sauce with blue cheese dip." },
  { id: 'us-sloppy', name: "Hidden-Veggie Sloppy Joes", cuisine: 'american', meal: 'Dinner', emoji: '🍔', time: 25, level: 'Easy', serves: 6,
    tags: ['hidden veg', 'one-pan'],
    ingredients: ["500 g lean ground beef or turkey", "1 carrot and ½ red pepper, very finely grated", "¾ cup ketchup", "¼ cup tomato sauce", "1 tbsp brown sugar", "1 tsp Worcestershire", "1 tsp mustard", "6 soft burger buns"],
    steps: ["Brown the meat, breaking it up small.", "Add the grated veg and cook 3 minutes until soft.", "Stir in ketchup, tomato sauce, sugar, Worcestershire and mustard; simmer 10 minutes.", "Spoon onto toasted buns."],
    picky: ["Grated veg melts right into the sauce — nobody sees it.", "Serve open-faced with a fork for kids who hate messy hands.", "Leftovers make great 'sloppy joe quesadillas'."],
    grownUp: "Top with pickled jalapeños and sharp cheddar." },
  { id: 'us-meatloaf', name: "Mini Meatloaf Muffins", cuisine: 'american', meal: 'Dinner', emoji: '🧁', time: 35, level: 'Easy', serves: 6,
    tags: ['portion-sized', 'make-ahead', 'lunchbox'],
    ingredients: ["700 g lean ground beef", "1 egg", "½ cup breadcrumbs", "¼ cup milk", "½ small onion, grated", "1 tsp salt", "½ cup ketchup + 1 tbsp brown sugar for the glaze"],
    steps: ["Heat oven to 375°F (190°C) and grease a 12-cup muffin tin.", "Mix beef, egg, crumbs, milk, onion and salt gently with your hands.", "Pack into cups, spread ketchup glaze on top.", "Bake 20–22 min until 160°F (71°C) inside."],
    picky: ["Top with a swirl of mashed potato 'frosting' to make meatloaf cupcakes.", "Small size = less intimidating than a slab of meatloaf."],
    grownUp: "Add chopped fresh herbs and a sriracha-ketchup glaze." },
  { id: 'us-grilledcheese', name: "Grilled Cheese & Tomato Soup Dippers", cuisine: 'american', meal: 'Lunch', emoji: '🥪', time: 20, level: 'Easy', serves: 4,
    tags: ['dippable', 'rainy day'],
    ingredients: ["8 slices bread", "Butter", "8 slices cheddar or mozzarella", "1 can (796 ml) crushed tomatoes", "1 cup chicken or veg broth", "½ cup milk or cream", "1 tsp sugar", "Salt"],
    steps: ["Simmer tomatoes, broth and sugar 10 minutes, then blend smooth and stir in milk; season.", "Butter the outside of the bread, add cheese, and cook in a pan over medium 2–3 min per side.", "Cut sandwiches into strips for dunking."],
    picky: ["Cut sandwiches with cookie cutters.", "Blend a roasted carrot into the soup for sweetness.", "Serve the soup in a mug so it feels like a drink."],
    grownUp: "Add caramelized onions and gruyère to adult sandwiches." },
  { id: 'us-frenchtoast', name: "French Toast Sticks", cuisine: 'american', meal: 'Breakfast', emoji: '🍞', time: 15, level: 'Easy', serves: 4,
    tags: ['dippable', 'freezer friendly'],
    ingredients: ["6 slices thick bread, cut in 3 strips each", "3 eggs", "¾ cup milk", "1 tsp cinnamon", "1 tsp vanilla", "Butter for the pan", "Maple syrup to dip"],
    steps: ["Whisk eggs, milk, cinnamon and vanilla in a shallow dish.", "Dip each stick quickly (don't soak).", "Cook in a buttered pan over medium until golden on all sides, about 4 min total."],
    picky: ["Serve syrup in a tiny cup for dipping — kids love control.", "Roll warm sticks in cinnamon sugar for a 'churro' version."],
    grownUp: "Serve with berries, whipped ricotta and crispy bacon." },
  { id: 'us-bbq', name: "Slow-Cooker BBQ Pulled Chicken Sliders", cuisine: 'american', meal: 'Dinner', emoji: '🥪', time: 15, cook: '3–6 hr slow cooker', level: 'Easy', serves: 8,
    tags: ['slow cooker', 'busy night', 'game day'],
    ingredients: ["900 g boneless chicken thighs", "1 cup mild BBQ sauce", "¼ cup apple juice", "1 tbsp brown sugar", "1 tsp garlic powder", "Slider buns", "Coleslaw (optional)"],
    steps: ["Put chicken in the slow cooker; mix BBQ sauce, juice, sugar and garlic and pour over.", "Cook on LOW 6 hours or HIGH 3 hours.", "Shred with two forks right in the sauce.", "Pile on buns."],
    picky: ["Perfect for practice nights — start it in the morning.", "Keep some chicken sauce-free for the 'plain please' kid.", "Serve with cheese slices kids can add themselves."],
    grownUp: "Top with slaw, pickles and hot BBQ sauce." },

  // ---------------- THAI ----------------
  { id: 'th-satay', name: "Mild Chicken Satay with Dipping Sauce", cuisine: 'thai', meal: 'Dinner', emoji: '🍢', time: 30, level: 'Easy', serves: 4,
    tags: ['on a stick', 'dippable', 'mild'],
    ingredients: ["600 g chicken thighs, in strips", "½ cup coconut milk", "1 tbsp soy sauce", "1 tbsp brown sugar", "1 tsp mild curry powder", "Sauce: ⅓ cup peanut or sunflower butter, ⅓ cup coconut milk, 1 tbsp soy, 1 tbsp honey, squeeze of lime"],
    steps: ["Marinate chicken in coconut milk, soy, sugar and curry powder for 15 min (or all day).", "Thread onto skewers (soak wooden ones 10 min).", "Grill or broil 4–5 min per side until 165°F (74°C).", "Warm sauce ingredients together, thin with water until dippable."],
    picky: ["Anything on a stick gets eaten — snip pointy ends for little ones.", "Use sunflower butter to keep it nut-free.", "Serve with plain rice and cucumber coins."],
    grownUp: "Add sriracha and chopped peanuts to the sauce, plus a quick cucumber-chili relish." },
  { id: 'th-padseeew', name: "Pad See Ew (Sweet Soy Noodles)", cuisine: 'thai', meal: 'Dinner', emoji: '🍜', time: 25, level: 'Medium', serves: 4,
    tags: ['noodles', 'sweet-savoury', 'no heat'],
    ingredients: ["400 g wide rice noodles", "300 g chicken, thinly sliced", "2 eggs", "2 cups broccoli florets (small)", "2 tbsp oil", "Sauce: 2 tbsp dark soy (or kecap manis), 1 tbsp soy, 1 tbsp oyster sauce, 1 tbsp brown sugar"],
    steps: ["Soak or cook noodles per package; drain and toss with a little oil.", "Mix the sauce.", "Stir-fry chicken in hot oil until cooked; push aside, scramble the eggs.", "Add broccoli and 2 tbsp water, cover 2 min, then add noodles and sauce; toss until caramelized."],
    picky: ["Sweet dark soy tastes like 'noodle candy' — no spice at all.", "Cut broccoli tiny so it hides in noodles, or leave out and serve on the side."],
    grownUp: "Finish with chili vinegar or chili flakes and a squeeze of lime." },
  { id: 'th-pineapple', name: "Pineapple Fried Rice", cuisine: 'thai', meal: 'Dinner', emoji: '🍍', time: 20, level: 'Easy', serves: 4,
    tags: ['leftover rice', 'sweet', 'one-pan'],
    ingredients: ["4 cups cold cooked jasmine rice", "1 cup pineapple chunks", "2 eggs", "1 cup cooked ham or chicken, diced", "½ cup frozen peas and carrots", "2 tbsp soy sauce", "1 tsp sugar", "1 tsp mild curry powder (optional)"],
    steps: ["Scramble eggs in an oiled wok, remove.", "Stir-fry ham and peas/carrots 2 min.", "Add rice, break up clumps, stir-fry until hot and a little crispy.", "Add pineapple, soy, sugar, curry powder and eggs; toss 1 minute."],
    picky: ["Serve in a hollowed pineapple half — instant 'restaurant' dinner.", "Pineapple sweetness wins over rice skeptics."],
    grownUp: "Add cashews, green onion and a spoon of chili crisp." },
  { id: 'th-curry', name: "Mild Coconut Yellow Curry", cuisine: 'thai', meal: 'Dinner', emoji: '🍛', time: 30, level: 'Easy', serves: 4,
    tags: ['creamy', 'mild', 'one-pot'],
    ingredients: ["500 g chicken, bite-sized", "1 can (400 ml) coconut milk", "1 tbsp mild yellow curry paste (or 2 tsp curry powder)", "2 potatoes, small cubes", "1 carrot, sliced", "1 tbsp fish sauce or soy", "1 tbsp brown sugar", "Jasmine rice"],
    steps: ["Simmer 3 tbsp of the coconut cream with curry paste 1 minute.", "Add chicken, stir to coat.", "Add remaining coconut milk, potatoes, carrot and ½ cup water; simmer 15–18 min until tender.", "Season with fish sauce and sugar; serve over rice."],
    picky: ["Start with just 1 tsp paste — you can add more to adult bowls.", "Potatoes make it familiar, like a creamy stew.", "Serve sauce on the side for 'no sauce' kids."],
    grownUp: "Stir red curry paste and Thai basil into adult portions." },
  { id: 'th-larb', name: "Chicken Lettuce Cups (Mild Larb)", cuisine: 'thai', meal: 'Lunch', emoji: '🥬', time: 20, level: 'Easy', serves: 4,
    tags: ['build-your-own', 'fresh', 'light'],
    ingredients: ["500 g ground chicken", "1 tbsp oil", "2 tbsp fish sauce or soy", "1 tbsp lime juice", "1 tbsp brown sugar", "Butter lettuce leaves", "Cucumber, carrot matchsticks, cooked rice"],
    steps: ["Cook chicken in oil, breaking it up, until no pink remains.", "Stir in fish sauce, lime juice and sugar.", "Set out lettuce, rice and veg; everyone builds their own cups."],
    picky: ["Build-your-own means kids choose what goes in.", "Rice-in-a-lettuce-taco is a great first step."],
    grownUp: "Add toasted rice powder, mint, shallots and chili flakes." },
  { id: 'th-mango', name: "Mango Sticky Rice", cuisine: 'thai', meal: 'Snack', emoji: '🥭', time: 35, cook: '1 hr soak', level: 'Medium', serves: 4,
    tags: ['dessert', 'weekend treat'],
    ingredients: ["1 cup glutinous (sticky) rice, soaked 1+ hour", "1 can (400 ml) coconut milk", "⅓ cup sugar", "½ tsp salt", "2 ripe mangoes, sliced"],
    steps: ["Steam soaked rice 20–25 min until tender and chewy.", "Warm ¾ of the coconut milk with sugar and salt; pour over hot rice and let it soak in 15 min.", "Simmer the rest of the coconut milk with a pinch of salt until slightly thick for drizzling.", "Serve rice with mango and the drizzle."],
    picky: ["It's dessert with fruit — an easy win.", "Use regular jasmine rice cooked in coconut milk if you can't find sticky rice."],
    grownUp: "Sprinkle toasted sesame seeds and a little lime zest." },

  // ---------------- CHINESE ----------------
  { id: 'cn-honeygarlic', name: "Honey Garlic Chicken", cuisine: 'chinese', meal: 'Dinner', emoji: '🍯', time: 25, level: 'Easy', serves: 4,
    tags: ['sticky', 'sweet', 'kid favourite'],
    ingredients: ["600 g chicken thighs, bite-sized", "3 tbsp cornstarch", "2 tbsp oil", "⅓ cup honey", "3 tbsp soy sauce", "2 cloves garlic, grated", "1 tbsp ketchup", "Rice to serve"],
    steps: ["Toss chicken in cornstarch.", "Pan-fry in oil over medium-high until golden and cooked through (8–10 min).", "Stir honey, soy, garlic and ketchup together; pour in and bubble 1–2 min until sticky."],
    picky: ["Grated garlic melts into the sauce — no chunks.", "Serve with steamed broccoli 'trees' to dip in the extra sauce."],
    grownUp: "Add chili flakes and toasted sesame seeds." },
  { id: 'cn-friedrice', name: "Classic Egg Fried Rice", cuisine: 'chinese', meal: 'Dinner', emoji: '🍚', time: 15, level: 'Easy', serves: 4,
    tags: ['leftover rice', 'quick', 'budget'],
    ingredients: ["4 cups cold cooked rice", "3 eggs", "2 tbsp oil", "¾ cup frozen peas and carrots", "2 green onions (optional)", "2 tbsp soy sauce", "1 tsp sesame oil"],
    steps: ["Scramble eggs in hot oil, break into small bits, remove.", "Stir-fry peas and carrots 2 min.", "Add rice and fry, pressing and tossing, until hot and slightly crispy.", "Add soy, sesame oil and egg; toss."],
    picky: ["'Rainbow rice' — let kids count the colours.", "Leave veg out of one portion and add ham or corn instead."],
    grownUp: "Top with a fried egg and chili oil." },
  { id: 'cn-lomein', name: "Chicken Lo Mein", cuisine: 'chinese', meal: 'Dinner', emoji: '🍜', time: 25, level: 'Easy', serves: 4,
    tags: ['noodles', 'takeout at home'],
    ingredients: ["350 g lo mein or spaghetti", "300 g chicken, thin strips", "1 cup snap peas or shredded cabbage", "1 carrot, matchsticks", "Sauce: 3 tbsp soy, 1 tbsp oyster sauce, 1 tbsp honey, 1 tsp sesame oil, 2 tbsp water"],
    steps: ["Cook noodles, drain and rinse briefly.", "Stir-fry chicken until cooked; add veg for 2 minutes.", "Add noodles and sauce; toss until glossy and hot."],
    picky: ["Spaghetti works perfectly — it looks familiar.", "Twirl it on chopsticks with a rubber band 'trainer'."],
    grownUp: "Add garlic, ginger and sambal oelek." },
  { id: 'cn-sweetsour', name: "Baked Sweet & Sour Chicken", cuisine: 'chinese', meal: 'Dinner', emoji: '🍗', time: 40, level: 'Medium', serves: 4,
    tags: ['sweet', 'baked not fried'],
    ingredients: ["600 g chicken breast, cubed", "½ cup cornstarch", "2 eggs, beaten", "Sauce: ½ cup sugar, ¼ cup ketchup, ⅓ cup rice vinegar, 1 tbsp soy, 1 tsp garlic powder", "1 cup pineapple chunks", "Rice"],
    steps: ["Heat oven to 325°F (160°C).", "Toss chicken in cornstarch, dip in egg, and sear in an oiled pan just until golden (not cooked through).", "Place in a baking dish, pour sauce over, add pineapple.", "Bake 30 min, stirring halfway, until sticky and 165°F (74°C) inside."],
    picky: ["Tastes like the takeout they love.", "Pineapple 'treasures' make fruit part of dinner."],
    grownUp: "Add peppers and onions and a pinch of chili flakes." },
  { id: 'cn-dumplings', name: "Pork & Cabbage Potstickers", cuisine: 'chinese', meal: 'Dinner', emoji: '🥟', time: 45, level: 'Medium', serves: 4,
    tags: ['family project', 'freezer friendly'],
    ingredients: ["400 g ground pork", "1½ cups finely chopped napa cabbage (salted, squeezed dry)", "2 tbsp soy sauce", "1 tsp sesame oil", "1 tsp grated ginger", "40 round dumpling wrappers", "Dip: soy sauce + a little rice vinegar + honey"],
    steps: ["Mix pork, cabbage, soy, sesame oil and ginger.", "Put 1 tsp filling in each wrapper, wet the edge, fold and pinch shut.", "Fry flat side down in an oiled pan 2 min, add ⅓ cup water, cover and steam 6 min.", "Uncover and fry until the bottoms crisp."],
    picky: ["Kids who fold their own dumplings eat their own dumplings.", "Freeze on a tray, then bag — cook from frozen (add 2 min steam)."],
    grownUp: "Add chili crisp to the dip." },
  { id: 'cn-eggdrop', name: "Egg Drop Soup", cuisine: 'chinese', meal: 'Lunch', emoji: '🥣', time: 10, level: 'Easy', serves: 4,
    tags: ['5 ingredients', 'sick day'],
    ingredients: ["6 cups chicken broth", "2 tbsp cornstarch mixed with 3 tbsp water", "3 eggs, beaten", "½ tsp sesame oil", "Salt and white pepper", "Corn kernels (optional)"],
    steps: ["Bring broth to a simmer, stir in cornstarch slurry until slightly thick.", "Stir the soup in a circle and slowly drizzle in eggs to make ribbons.", "Turn off heat, add sesame oil, season."],
    picky: ["Call it 'cloud soup'.", "Add creamed corn for a sweeter version kids love."],
    grownUp: "Add tofu, green onion and chili oil." },
  { id: 'cn-beefbroc', name: "Beef & Broccoli", cuisine: 'chinese', meal: 'Dinner', emoji: '🥦', time: 20, level: 'Easy', serves: 4,
    tags: ['quick', 'high protein'],
    ingredients: ["500 g flank steak, thinly sliced across the grain", "1 tbsp cornstarch", "3 cups small broccoli florets", "2 tbsp oil", "Sauce: ¼ cup soy, 2 tbsp brown sugar, 1 tbsp oyster sauce, ½ cup broth, 1 tsp cornstarch"],
    steps: ["Toss beef with cornstarch.", "Sear beef in hot oil in batches, remove.", "Add broccoli and 3 tbsp water, cover 2 min.", "Add sauce and beef, simmer until glossy."],
    picky: ["Thin slicing makes the beef tender and less 'chewy'.", "Serve a kid bowl with broccoli on the side, not mixed."],
    grownUp: "Add fresh ginger and garlic and a dash of rice wine." },

  // ---------------- JAPANESE ----------------
  { id: 'jp-teriyaki', name: "Chicken Teriyaki Rice Bowls", cuisine: 'japanese', meal: 'Dinner', emoji: '🍱', time: 25, level: 'Easy', serves: 4,
    tags: ['sticky', 'bowl', 'lunchbox leftovers'],
    ingredients: ["600 g chicken thighs", "Sauce: ¼ cup soy sauce, 2 tbsp mirin (or 1 tbsp sugar), 2 tbsp honey, 1 tsp grated ginger", "1 tsp cornstarch in 1 tbsp water", "Rice, cucumber, edamame, sesame seeds"],
    steps: ["Pan-sear chicken skin-side down (or just thighs) over medium until golden, flip and cook through.", "Add sauce and simmer, turning, until sticky; stir in cornstarch slurry.", "Slice and serve over rice with cucumber and edamame."],
    picky: ["Bowls with separate little piles = no 'touching foods' drama.", "Extra sauce on rice makes it 'candy rice'."],
    grownUp: "Top with pickled ginger, spicy mayo and furikake." },
  { id: 'jp-onigiri', name: "Onigiri Rice Balls", cuisine: 'japanese', meal: 'Lunch', emoji: '🍙', time: 25, level: 'Easy', serves: 6,
    tags: ['lunchbox', 'hands-on', 'finger food'],
    ingredients: ["3 cups cooked Japanese short-grain rice, warm", "Salt", "Fillings: canned tuna + mayo, flaked salmon, or cheese cubes", "Nori sheets, cut in strips", "Furikake (optional)"],
    steps: ["Wet hands and rub with a pinch of salt.", "Flatten a scoop of rice in your palm, add a spoon of filling, close the rice around it.", "Press into a triangle or ball; wrap with a nori strip."],
    picky: ["Let kids pick fillings — even plain buttered rice balls count.", "Add nori 'faces' to make characters."],
    grownUp: "Fill with spicy salmon or umeboshi." },
  { id: 'jp-katsu', name: "Chicken Katsu with Sweet Katsu Sauce", cuisine: 'japanese', meal: 'Dinner', emoji: '🍛', time: 30, level: 'Medium', serves: 4,
    tags: ['crispy', 'dippable'],
    ingredients: ["2 chicken breasts, butterflied and pounded thin", "½ cup flour", "2 eggs", "1½ cups panko", "Oil for pan-frying", "Sauce: ¼ cup ketchup, 2 tbsp Worcestershire, 1 tbsp soy, 1 tbsp sugar", "Rice and shredded cabbage"],
    steps: ["Season chicken; dredge in flour, then egg, then panko.", "Shallow-fry in ½ inch of oil over medium, 3–4 min per side, until golden and 165°F (74°C).", "Stir sauce ingredients together.", "Slice katsu into strips and serve with rice."],
    picky: ["It's basically a big chicken nugget — tell them so.", "Katsu sauce tastes like fancy ketchup."],
    grownUp: "Serve with Japanese curry sauce and Kewpie mayo." },
  { id: 'jp-yakiudon', name: "Yaki Udon Stir-Fry", cuisine: 'japanese', meal: 'Dinner', emoji: '🍜', time: 20, level: 'Easy', serves: 4,
    tags: ['thick noodles', 'quick'],
    ingredients: ["4 packs frozen or vacuum udon", "250 g chicken or pork, thin slices", "2 cups cabbage, shredded", "1 carrot, matchsticks", "Sauce: 3 tbsp soy, 1 tbsp oyster sauce, 1 tbsp mirin or honey, 1 tsp sugar"],
    steps: ["Loosen udon in hot water 1 minute, drain.", "Stir-fry meat until cooked, add veg 2 min.", "Add udon and sauce, toss 2 min until coated."],
    picky: ["Chunky 'worm noodles' are fun to slurp.", "Keep a plain buttered udon bowl for the pickiest."],
    grownUp: "Finish with bonito flakes and shichimi pepper." },
  { id: 'jp-tamago', name: "Tamagoyaki (Sweet Rolled Omelette)", cuisine: 'japanese', meal: 'Breakfast', emoji: '🍳', time: 15, level: 'Medium', serves: 2,
    tags: ['eggs', 'lunchbox'],
    ingredients: ["4 eggs", "1 tbsp sugar", "1 tsp soy sauce", "2 tbsp milk or water", "Oil"],
    steps: ["Whisk eggs, sugar, soy and milk.", "Pour a thin layer into an oiled non-stick pan over medium-low; when almost set, roll it to one side.", "Pour another thin layer, lift the roll so egg flows under, roll back over. Repeat.", "Rest 2 min, slice into rounds."],
    picky: ["Slightly sweet eggs win over 'I don't like eggs' kids.", "Roll a slice of ham or cheese inside."],
    grownUp: "Add dashi and green onion for a savoury version." },
  { id: 'jp-curry', name: "Japanese Curry Rice (Mild)", cuisine: 'japanese', meal: 'Dinner', emoji: '🍛', time: 40, level: 'Easy', serves: 6,
    tags: ['mild', 'one-pot', 'make-ahead'],
    ingredients: ["500 g chicken or beef, bite-sized", "1 onion, sliced", "2 carrots, chunks", "2 potatoes, chunks", "1 box Japanese curry roux, MILD (half box for 4)", "4 cups water", "1 grated apple (optional)", "Rice"],
    steps: ["Brown meat and onion in a pot.", "Add carrots, potatoes and water; simmer 15–20 min until tender.", "Turn off heat, add roux pieces and grated apple; stir until melted.", "Simmer 5 min until thick; serve over rice."],
    picky: ["Mild roux is sweet, not spicy — like a gravy stew.", "Serve the curry beside the rice, not on top, for cautious kids."],
    grownUp: "Use the 'hot' roux or add chili oil and a fried egg." },

  // ---------------- ITALIAN ----------------
  { id: 'it-hiddenveg', name: "Hidden-Veggie Tomato Pasta", cuisine: 'italian', meal: 'Dinner', emoji: '🍝', time: 30, level: 'Easy', serves: 4,
    tags: ['hidden veg', 'batch sauce', 'freezer friendly'],
    ingredients: ["400 g pasta", "1 tbsp olive oil", "1 carrot, 1 small zucchini, ½ red pepper — chopped", "1 can (796 ml) crushed tomatoes", "1 tsp sugar", "1 tsp salt", "½ cup grated parmesan"],
    steps: ["Soften veg in olive oil 8 minutes.", "Add tomatoes, sugar and salt; simmer 15 min.", "Blend completely smooth.", "Toss with cooked pasta and parmesan."],
    picky: ["Smooth sauce = zero visible veg.", "Make a triple batch and freeze in cups."],
    grownUp: "Add garlic, chili flakes and fresh basil." },
  { id: 'it-pizza', name: "Build-Your-Own Pizza Night", cuisine: 'italian', meal: 'Dinner', emoji: '🍕', time: 30, level: 'Easy', serves: 4,
    tags: ['build-your-own', 'family night', 'Friday'],
    ingredients: ["4 naan or small pizza crusts", "¾ cup pizza sauce", "2 cups shredded mozzarella", "Toppings bar: pepperoni, ham, pineapple, peppers, olives, mushrooms"],
    steps: ["Heat oven to 425°F (220°C).", "Everyone spreads sauce and picks toppings.", "Bake on a sheet pan 10–12 min until bubbly and golden."],
    picky: ["Kids who build it, eat it — even if it's just cheese.", "Offer one 'new' topping each week and see who tries it."],
    grownUp: "Hot honey, prosciutto and arugula after baking." },
  { id: 'it-meatballs', name: "Mini Meatballs & Spaghetti", cuisine: 'italian', meal: 'Dinner', emoji: '🍝', time: 40, level: 'Medium', serves: 6,
    tags: ['freezer friendly', 'classic'],
    ingredients: ["500 g lean ground beef (or half pork)", "1 egg", "½ cup breadcrumbs", "¼ cup milk", "¼ cup parmesan", "1 tsp salt", "1 jar (650 ml) marinara", "450 g spaghetti"],
    steps: ["Mix beef, egg, crumbs, milk, parmesan and salt; roll into marble-size balls.", "Bake at 400°F (200°C) 12–14 min.", "Simmer meatballs in marinara 10 min.", "Serve over spaghetti."],
    picky: ["Marble-size meatballs are more fun and less scary.", "Kids can roll the meatballs."],
    grownUp: "Add fennel seed and chili to the mix; top with ricotta." },
  { id: 'it-parm', name: "Baked Chicken Parmesan", cuisine: 'italian', meal: 'Dinner', emoji: '🧀', time: 35, level: 'Easy', serves: 4,
    tags: ['crispy', 'cheesy'],
    ingredients: ["2 chicken breasts, halved into cutlets", "1 egg", "1 cup Italian breadcrumbs", "¼ cup parmesan", "1 cup marinara", "1 cup shredded mozzarella", "Pasta or garlic bread"],
    steps: ["Heat oven to 425°F (220°C).", "Dip cutlets in egg, then crumbs mixed with parmesan; bake on a greased rack 15 min.", "Top each with marinara and mozzarella; bake 5–8 min more until bubbly and 165°F (74°C)."],
    picky: ["Sauce under the cheese, not everywhere, for sauce-averse kids.", "Slice into 'pizza chicken' strips."],
    grownUp: "Serve on a crusty roll with fresh basil and chili flakes." },
  { id: 'it-burro', name: "Pasta al Burro (Butter & Parmesan Pasta)", cuisine: 'italian', meal: 'Lunch', emoji: '🧈', time: 12, level: 'Easy', serves: 4,
    tags: ['ultimate picky', '3 ingredients'],
    ingredients: ["400 g short pasta or spaghetti", "4 tbsp butter", "¾ cup finely grated parmesan", "Salt"],
    steps: ["Cook pasta in well-salted water; save 1 cup pasta water.", "Toss drained pasta with butter and ½ cup pasta water over low heat.", "Add parmesan and toss until creamy, adding more water if needed."],
    picky: ["The 'safe food' for tough days — pair with one fruit they like.", "Stir in peas for the brave ones."],
    grownUp: "Add lemon zest, black pepper and garlic (cacio e pepe style)." },
  { id: 'it-rollups', name: "Lasagna Roll-Ups", cuisine: 'italian', meal: 'Dinner', emoji: '🌯', time: 45, level: 'Medium', serves: 6,
    tags: ['portion-sized', 'make-ahead'],
    ingredients: ["12 lasagna noodles, cooked", "475 g ricotta", "1 cup shredded mozzarella + 1 cup for top", "½ cup parmesan", "1 egg", "1 cup chopped spinach (optional)", "1 jar (650 ml) marinara"],
    steps: ["Heat oven to 375°F (190°C). Spread 1 cup marinara in a baking dish.", "Mix ricotta, 1 cup mozzarella, parmesan, egg and spinach.", "Spread on each noodle and roll up; set seam-side down.", "Top with remaining sauce and mozzarella; cover and bake 25 min, uncover 10 min."],
    picky: ["Individual rolls = everyone gets 'their own lasagna'.", "Blend the spinach into the ricotta so it's just 'green cheese'."],
    grownUp: "Add Italian sausage to the sauce." },

  // ---------------- MEXICAN ----------------
  { id: 'mx-tacos', name: "Build-Your-Own Taco Night", cuisine: 'mexican', meal: 'Dinner', emoji: '🌮', time: 25, level: 'Easy', serves: 4,
    tags: ['build-your-own', 'Tuesday'],
    ingredients: ["500 g ground beef or turkey", "Mild seasoning: 1 tsp cumin, 1 tsp paprika, 1 tsp garlic powder, ½ tsp oregano, ½ tsp salt", "⅓ cup water", "Hard shells and soft tortillas", "Toppings: cheese, lettuce, tomato, sour cream, mild salsa, corn"],
    steps: ["Brown the meat.", "Add seasoning and water; simmer until saucy.", "Warm shells; set out a toppings bar and let everyone build."],
    picky: ["Homemade mild seasoning avoids the hidden spice in packets.", "A 'taco plate' (meat, cheese, chips separately) is still taco night."],
    grownUp: "Pickled onions, cilantro, lime and hot sauce." },
  { id: 'mx-quesadilla', name: "Cheesy Chicken Quesadillas", cuisine: 'mexican', meal: 'Lunch', emoji: '🫓', time: 15, level: 'Easy', serves: 4,
    tags: ['leftover chicken', 'dippable'],
    ingredients: ["8 small flour tortillas", "2 cups shredded cheddar/Monterey Jack", "1½ cups cooked shredded chicken", "½ cup corn or black beans (optional)", "Sour cream and mild salsa to dip"],
    steps: ["Sprinkle cheese, chicken and extras on half of each tortilla; fold.", "Cook in a dry pan over medium 2–3 min per side until golden and melty.", "Cut into triangles."],
    picky: ["Cheese-only quesadillas count — add chicken next time.", "Blend black beans smooth and spread thin inside — invisible."],
    grownUp: "Add jalapeños, chorizo and pickled red onion." },
  { id: 'mx-bowl', name: "Burrito Bowls", cuisine: 'mexican', meal: 'Dinner', emoji: '🥙', time: 30, level: 'Easy', serves: 4,
    tags: ['bowl', 'build-your-own', 'meal prep'],
    ingredients: ["500 g chicken breast", "1 tsp each cumin, paprika, garlic powder; ½ tsp salt", "2 cups rice cooked with a squeeze of lime", "1 can black beans, warmed", "1 cup corn", "Cheese, avocado, sour cream, mild salsa"],
    steps: ["Season chicken and pan-cook 5–6 min per side to 165°F (74°C); rest and slice.", "Set out rice, beans, corn, chicken and toppings.", "Everyone builds a bowl."],
    picky: ["Deconstructed = picky-proof.", "Crushed tortilla chips on top make any bowl exciting."],
    grownUp: "Chipotle crema and fresh pico de gallo." },
  { id: 'mx-enchiladas', name: "Mild Cheesy Chicken Enchiladas", cuisine: 'mexican', meal: 'Dinner', emoji: '🌯', time: 40, level: 'Medium', serves: 6,
    tags: ['make-ahead', 'cheesy'],
    ingredients: ["3 cups cooked shredded chicken", "2½ cups shredded cheese", "½ cup sour cream", "8 flour tortillas", "2 cups mild red enchilada sauce (or tomato sauce + 1 tsp cumin)"],
    steps: ["Heat oven to 375°F (190°C); spread ½ cup sauce in a baking dish.", "Mix chicken, sour cream and 1 cup cheese.", "Fill and roll tortillas; place seam-side down.", "Top with sauce and remaining cheese; bake 20 min."],
    picky: ["Make a couple 'cheese only' rolls on one end of the pan.", "Sour cream in the filling cools any spice."],
    grownUp: "Add green chiles and top with cilantro and hot sauce." },
  { id: 'mx-fajitas', name: "Sheet-Pan Chicken Fajitas", cuisine: 'mexican', meal: 'Dinner', emoji: '🫑', time: 30, level: 'Easy', serves: 4,
    tags: ['one-pan', 'busy night'],
    ingredients: ["600 g chicken breast, strips", "3 bell peppers, strips", "1 onion, sliced", "2 tbsp oil", "Seasoning: 2 tsp paprika, 1 tsp cumin, 1 tsp garlic powder, ½ tsp salt", "Tortillas, cheese, sour cream"],
    steps: ["Heat oven to 425°F (220°C).", "Toss chicken and veg with oil and seasoning on a sheet pan.", "Roast 18–20 min, stirring once.", "Wrap in warm tortillas."],
    picky: ["Keep kid chicken on its own corner of the pan, unseasoned if needed.", "Sweet red/yellow peppers are easier than green."],
    grownUp: "Add chipotle or cayenne to the seasoning." },
  { id: 'mx-breakfast', name: "Breakfast Burritos", cuisine: 'mexican', meal: 'Breakfast', emoji: '🌯', time: 20, level: 'Easy', serves: 6,
    tags: ['freezer friendly', 'grab-and-go'],
    ingredients: ["8 eggs", "¼ cup milk", "1 cup cooked diced potatoes or hash browns", "1 cup cooked sausage or bacon bits", "1½ cups shredded cheese", "6 large flour tortillas"],
    steps: ["Scramble eggs with milk until just set.", "Warm tortillas; fill with eggs, potatoes, meat and cheese.", "Roll tightly; toast seam-side down in a pan 1 min.", "Wrap extras in foil and freeze; reheat 1–2 min in the microwave (unwrapped, in paper towel)."],
    picky: ["Mini burritos in small tortillas for small hands.", "Ketchup is a totally legit burrito sauce."],
    grownUp: "Add salsa verde, avocado and pickled jalapeños." },
  { id: 'mx-crisps', name: "Cinnamon Sugar Tortilla Crisps & Fruit Salsa", cuisine: 'mexican', meal: 'Snack', emoji: '🍓', time: 15, level: 'Easy', serves: 4,
    tags: ['dessert', 'fruit'],
    ingredients: ["4 flour tortillas", "2 tbsp melted butter", "3 tbsp sugar + 1 tsp cinnamon", "Fruit salsa: 1 cup diced strawberries, 1 apple diced, 1 kiwi diced, 1 tbsp honey, squeeze of lime"],
    steps: ["Heat oven to 375°F (190°C).", "Brush tortillas with butter, sprinkle cinnamon sugar, cut into wedges.", "Bake 8–10 min until crisp.", "Stir fruit salsa ingredients together and dip."],
    picky: ["Chips + fruit = the easiest fruit win of the week.", "Let them choose the fruits."],
    grownUp: "Add a pinch of chili-lime seasoning (Tajín) to the fruit." },
];


// ---------------- HEALTHY + MEAL PREP ADDITIONS ----------------
const MORE = [
  { id: 'ca-oats', name: "Overnight Oats 3 Ways", cuisine: 'canadian', meal: 'Breakfast', emoji: '🥣', time: 10, level: 'Easy', serves: 5,
    healthy: true, tags: ['no-cook', 'make-ahead', 'fibre'], prep: { makes: '5 jars', keeps: '4 days in the fridge', reheat: 'Eat cold, or microwave 1 min' },
    ingredients: ["2½ cups large-flake oats", "2½ cups milk (any kind)", "1¼ cups plain or vanilla yogurt", "2 tbsp chia seeds", "2 tbsp maple syrup", "Toppings: blueberries + cinnamon · banana + sunflower butter · apple + maple"],
    steps: ["Stir oats, milk, yogurt, chia and maple syrup together.", "Divide into 5 jars or containers.", "Top each with a flavour combo, lid, and refrigerate overnight.", "Grab-and-go breakfasts for the whole school week."],
    picky: ["Let each kid pick their topping and write their name on the lid.", "Blend it smooth for texture-sensitive kids — it becomes a 'breakfast pudding'.", "Mini chocolate chips on top are a fine gateway."],
    grownUp: "Add hemp hearts, nuts and a spoon of nut butter for more protein." },
  { id: 'us-eggmuffins', name: "Egg Muffin Cups (Mini Frittatas)", cuisine: 'american', meal: 'Breakfast', emoji: '🧁', time: 30, level: 'Easy', serves: 12,
    healthy: true, tags: ['high protein', 'freezer friendly', 'grab-and-go'], prep: { makes: '12 cups', keeps: '4 days fridge', freezer: '2 months', reheat: 'Microwave 30–45 sec' },
    ingredients: ["10 eggs", "¼ cup milk", "1 cup shredded cheddar", "1 cup finely chopped veg (peppers, spinach, broccoli)", "½ cup diced ham or cooked turkey sausage", "½ tsp salt"],
    steps: ["Heat oven to 350°F (175°C); grease or line a 12-cup muffin tin.", "Whisk eggs, milk and salt.", "Divide cheese, veg and ham among cups; pour egg over (¾ full).", "Bake 18–22 min until set in the centre. Cool, then refrigerate or freeze."],
    picky: ["Make a few 'cheese only' cups — mark them with a ham piece on top.", "Chop veg tiny or blitz in a food processor so it's confetti."],
    grownUp: "Add feta, sun-dried tomato and hot sauce." },
  { id: 'mx-sweetpotato', name: "Sweet Potato & Black Bean Quesadillas", cuisine: 'mexican', meal: 'Lunch', emoji: '🍠', time: 25, level: 'Easy', serves: 6,
    healthy: true, tags: ['vegetarian', 'freezer friendly', 'fibre'], prep: { makes: '6 quesadillas', keeps: '3 days fridge', freezer: '2 months', reheat: 'Dry pan 3 min per side, or 400°F oven 10 min' },
    ingredients: ["1 large sweet potato, peeled and cubed", "1 can black beans, rinsed", "1 tsp cumin", "½ tsp garlic powder", "1½ cups shredded cheddar or Tex-Mex cheese", "6 large whole-wheat tortillas", "Salsa and plain yogurt to dip"],
    steps: ["Microwave or boil sweet potato until very soft (8–10 min); mash.", "Mash in half the beans with cumin, garlic and a pinch of salt; stir in the rest.", "Spread on half of each tortilla, add cheese, fold.", "Cook in a dry pan 2–3 min per side until golden."],
    picky: ["Mashed sweet potato tastes sweet and hides the beans.", "Serve with a yogurt 'sour cream' dip."],
    grownUp: "Add chipotle, pickled onion and cilantro." },
  { id: 'jp-salmonbowl', name: "Teriyaki Salmon Rice Bowls", cuisine: 'japanese', meal: 'Dinner', emoji: '🍣', time: 25, level: 'Easy', serves: 4,
    healthy: true, tags: ['omega-3', 'bowl', 'quick'],
    ingredients: ["4 salmon fillets (or 600 g salmon cubes)", "3 tbsp soy sauce (low sodium)", "2 tbsp honey", "1 tsp grated ginger", "Brown or white rice", "Cucumber, shredded carrot, edamame, avocado", "Sesame seeds"],
    steps: ["Heat oven to 400°F (200°C). Mix soy, honey and ginger.", "Brush salmon with half the sauce; bake 10–12 min until it flakes.", "Brush with the rest, broil 1 min.", "Build bowls: rice, flaked salmon, veg piles, sesame seeds."],
    picky: ["Flake the salmon into the rice with extra sauce — like 'sweet fish rice'.", "Veg in separate piles so kids choose.", "Cooked salmon only — no raw fish worries."],
    grownUp: "Add sriracha mayo, pickled ginger and nori strips." },
  { id: 'th-freshrolls', name: "Fresh Spring Rolls with Sweet Chili Dip", cuisine: 'thai', meal: 'Lunch', emoji: '🥢', time: 30, level: 'Medium', serves: 4,
    healthy: true, tags: ['fresh', 'build-your-own', 'veggie-packed'],
    ingredients: ["12 rice paper wrappers", "Cooked shrimp or shredded chicken", "Rice vermicelli, cooked and cooled", "Cucumber, carrot, red pepper — matchsticks", "Lettuce leaves", "Dip: sweet chili sauce + squeeze of lime (or sunflower butter dip)"],
    steps: ["Set out fillings in bowls.", "Dip one rice paper in warm water 5–10 seconds; lay flat.", "Add lettuce, noodles, protein, veg; fold sides in and roll tightly.", "Serve with dip. Best eaten within a few hours."],
    picky: ["Rolling your own = eating your own.", "See-through wrappers let kids see there's nothing 'weird' inside."],
    grownUp: "Add mint, Thai basil and a spicy peanut-hoisin dip." },
  { id: 'cn-stirfry', name: "Chicken & Rainbow Veggie Stir-Fry", cuisine: 'chinese', meal: 'Dinner', emoji: '🥕', time: 25, level: 'Easy', serves: 4,
    healthy: true, tags: ['veggie-packed', 'high protein', 'one-pan'],
    ingredients: ["500 g chicken breast, thin strips", "1 tbsp cornstarch", "4 cups mixed veg: broccoli, snap peas, carrot coins, red pepper", "1 tbsp oil", "Sauce: 3 tbsp low-sodium soy, 1 tbsp honey, 1 tsp sesame oil, 1 tsp cornstarch, ¼ cup water", "Brown rice"],
    steps: ["Toss chicken with cornstarch; stir-fry in hot oil until cooked, remove.", "Stir-fry hard veg (carrot, broccoli) 3 min with 2 tbsp water, then peppers and peas 2 min.", "Return chicken, add sauce, toss until glossy.", "Serve over brown rice."],
    picky: ["Count the colours — 'eat the rainbow' challenge with a sticker.", "Keep veg crisp-tender; mushy veg is the #1 turn-off."],
    grownUp: "Add garlic, ginger and chili crisp." },
  { id: 'it-minestrone', name: "Minestrone with Tiny Pasta", cuisine: 'italian', meal: 'Dinner', emoji: '🥣', time: 40, level: 'Easy', serves: 8,
    healthy: true, tags: ['veggie-packed', 'freezer friendly', 'one-pot'], prep: { makes: '8 bowls', keeps: '4 days fridge', freezer: '3 months (freeze without pasta)', reheat: 'Stovetop with a splash of water' },
    ingredients: ["2 tbsp olive oil", "1 onion, 2 carrots, 2 celery — finely diced", "1 zucchini, diced", "1 can (796 ml) diced tomatoes", "6 cups low-sodium broth", "1 can white kidney beans, rinsed", "1 cup tiny pasta (ditalini or stars)", "Parmesan to serve"],
    steps: ["Soften onion, carrot and celery in oil 8 min.", "Add zucchini, tomatoes and broth; simmer 15 min.", "Add beans and pasta; simmer until pasta is tender (8–10 min).", "Season; top with parmesan."],
    picky: ["Star-shaped pasta makes it 'star soup'.", "Blend half the soup smooth so veg pieces are fewer."],
    grownUp: "Stir in pesto and chili flakes." },
  { id: 'ca-sheetpan', name: "Sheet-Pan Maple Dijon Chicken & Veggies", cuisine: 'canadian', meal: 'Dinner', emoji: '🍁', time: 40, level: 'Easy', serves: 4,
    healthy: true, tags: ['one-pan', 'high protein', 'meal prep'], prep: { makes: '4–5 containers', keeps: '4 days fridge', reheat: 'Microwave 2 min' },
    ingredients: ["700 g boneless chicken thighs", "2 tbsp maple syrup", "2 tbsp Dijon mustard", "1 tbsp olive oil", "3 cups baby potatoes, halved", "2 cups broccoli florets", "2 carrots, sticks", "Salt"],
    steps: ["Heat oven to 425°F (220°C).", "Toss potatoes and carrots with oil and salt; roast 15 min.", "Mix maple and Dijon; coat chicken. Add chicken and broccoli to the pan.", "Roast 20 min more until chicken is 165°F (74°C)."],
    picky: ["Maple wins over mustard — it tastes sweet, not tangy.", "Roasted carrots get candy-sweet; call them 'carrot fries'."],
    grownUp: "Add grainy mustard, garlic and rosemary." },
  { id: 'us-parfait', name: "Build-Your-Own Yogurt Parfait Bar", cuisine: 'american', meal: 'Snack', emoji: '🍓', time: 10, level: 'Easy', serves: 4,
    healthy: true, tags: ['no-cook', 'high protein', 'fruit'],
    ingredients: ["3 cups plain or vanilla Greek yogurt", "2 cups berries and chopped fruit", "1 cup low-sugar granola or crushed cereal", "Honey or maple to drizzle", "Hemp hearts or ground flax (optional)"],
    steps: ["Set out yogurt, fruit and crunchy toppings in bowls.", "Everyone layers their own in a clear cup.", "Drizzle a little honey on top."],
    picky: ["Clear cups make it look like dessert.", "Freeze leftovers in popsicle moulds for 'yogurt pops'."],
    grownUp: "Add nuts, seeds and a spoon of nut butter." },
  { id: 'mx-tortillasoup', name: "Mild Chicken Tortilla Soup", cuisine: 'mexican', meal: 'Dinner', emoji: '🍲', time: 35, level: 'Easy', serves: 6,
    healthy: true, tags: ['freezer friendly', 'one-pot'], prep: { makes: '6 bowls', keeps: '4 days fridge', freezer: '3 months', reheat: 'Stovetop until steaming' },
    ingredients: ["500 g chicken breast", "1 onion, diced", "1 tsp cumin, 1 tsp paprika", "1 can (796 ml) diced tomatoes", "6 cups low-sodium chicken broth", "1 can black beans, rinsed", "1 cup corn", "Toppings: crushed tortilla chips, cheese, avocado, yogurt"],
    steps: ["Soften onion with spices in a little oil.", "Add tomatoes, broth and whole chicken breasts; simmer 20 min.", "Remove chicken, shred, and return with beans and corn; simmer 5 min.", "Top bowls with chips and cheese."],
    picky: ["Crunchy chip topping = kid magnet.", "Strain a bowl of just broth, chicken and corn for the pickiest."],
    grownUp: "Add chipotle, lime and cilantro." },
  { id: 'us-chili', name: "Slow-Cooker Turkey Chili (Mild)", cuisine: 'american', meal: 'Dinner', emoji: '🌶️', time: 20, cook: '6–8 hr slow cooker', level: 'Easy', serves: 8,
    healthy: true, tags: ['slow cooker', 'freezer friendly', 'high protein', 'meal prep'], prep: { makes: '8 bowls', keeps: '4 days fridge', freezer: '3 months', reheat: 'Microwave 2–3 min, stir halfway' },
    ingredients: ["700 g lean ground turkey", "1 onion, finely diced", "1 red pepper, finely diced", "2 cans kidney or black beans, rinsed", "1 can (796 ml) crushed tomatoes", "1 cup corn", "1 tbsp mild chili powder, 1 tsp cumin, 1 tsp garlic powder", "Cheese and plain yogurt to top"],
    steps: ["Brown turkey with onion (optional but tastier).", "Add everything to the slow cooker.", "Cook LOW 6–8 hours or HIGH 3–4 hours.", "Portion leftovers into containers for lunches."],
    picky: ["Serve over rice or on a baked potato so it's familiar.", "Lots of cheese on top — then 'chili nachos' with tortilla chips."],
    grownUp: "Add chipotle, jalapeño and hot sauce." },
  { id: 'it-pastajars', name: "Pasta Salad Lunch Jars", cuisine: 'italian', meal: 'Lunch', emoji: '🥗', time: 20, level: 'Easy', serves: 5,
    healthy: true, tags: ['lunchbox', 'no reheat', 'meal prep'], prep: { makes: '5 lunches', keeps: '4 days fridge', reheat: 'Eat cold' },
    ingredients: ["350 g rotini (whole-wheat if you like)", "1 cup cherry tomatoes, halved", "1 cucumber, diced", "1 cup mozzarella pearls or cubes", "1 cup diced chicken or ham", "Dressing: ¼ cup olive oil, 2 tbsp red wine vinegar, 1 tsp honey, ½ tsp Italian seasoning, salt"],
    steps: ["Cook pasta, rinse under cold water, drain well.", "Shake dressing in a jar.", "Toss pasta with dressing, then divide into containers with the add-ins.", "Keep a few 'plain pasta + cheese' jars for picky kids."],
    picky: ["Deconstructed jar: pasta at the bottom, each add-in in its own layer.", "Mozzarella pearls are the draw."],
    grownUp: "Add olives, red onion, salami and feta." },
  { id: 'ca-muffins', name: "Banana Oat Muffins (No Refined Sugar)", cuisine: 'canadian', meal: 'Snack', emoji: '🍌', time: 30, level: 'Easy', serves: 12,
    healthy: true, tags: ['lunchbox', 'freezer friendly', 'nut-free'], prep: { makes: '12 muffins', keeps: '3 days on counter', freezer: '3 months', reheat: 'Thaw in lunchbox by snack time' },
    ingredients: ["3 very ripe bananas, mashed", "2 eggs", "⅓ cup maple syrup", "¼ cup melted butter or oil", "1 tsp vanilla", "1½ cups whole-wheat flour", "1 cup quick oats", "1 tsp baking soda, 1 tsp cinnamon, ¼ tsp salt", "½ cup mini chocolate chips or blueberries (optional)"],
    steps: ["Heat oven to 350°F (175°C); line a muffin tin.", "Whisk bananas, eggs, maple, butter and vanilla.", "Stir in flour, oats, baking soda, cinnamon and salt just until combined; fold in extras.", "Bake 18–22 min until a toothpick comes out clean."],
    picky: ["Mini muffins (bake 12–14 min) feel like a treat.", "Chocolate chips on top only — kids see them first."],
    grownUp: "Add walnuts and a crumble top." },
  { id: 'th-noodlejars', name: "Sunflower Noodle Salad Jars", cuisine: 'thai', meal: 'Lunch', emoji: '🍜', time: 20, level: 'Easy', serves: 4,
    healthy: true, tags: ['nut-free', 'lunchbox', 'meal prep'], prep: { makes: '4 lunches', keeps: '3 days fridge', reheat: 'Eat cold' },
    ingredients: ["250 g spaghetti or rice noodles", "Sauce: ⅓ cup sunflower seed butter, 3 tbsp soy, 2 tbsp honey, 1 tbsp rice vinegar, warm water to thin", "2 cups shredded chicken or edamame", "1 cup shredded carrot", "1 cucumber, matchsticks", "1 red pepper, thin strips"],
    steps: ["Cook noodles, rinse cold and drain.", "Whisk sauce until smooth and pourable.", "Toss noodles with sauce; divide into containers.", "Top with chicken and veg (keep separate for picky eaters)."],
    picky: ["'Peanut-butter noodles' — but school-safe.", "Veg on the side in a bento compartment."],
    grownUp: "Add sriracha, lime, cilantro and crushed peanuts." },
  { id: 'mx-salsachicken', name: "Salsa Shredded Chicken — 3 Meals", cuisine: 'mexican', meal: 'Dinner', emoji: '🐔', time: 10, cook: '4–6 hr slow cooker', level: 'Easy', serves: 10,
    healthy: true, tags: ['slow cooker', 'meal prep', 'high protein'], prep: { makes: '≈ 8 cups shredded chicken', keeps: '4 days fridge', freezer: '3 months', reheat: 'Microwave or pan with a splash of broth' },
    ingredients: ["1.3 kg boneless chicken breasts or thighs", "1½ cups mild salsa", "1 tsp cumin", "1 tsp garlic powder", "½ tsp salt", "Use it for: tacos, quesadillas, burrito bowls, soup"],
    steps: ["Put chicken in the slow cooker, top with salsa and spices.", "Cook LOW 5–6 hours or HIGH 3–4 hours.", "Shred in the juices.", "Portion: Mon tacos, Wed quesadillas, freeze the rest."],
    picky: ["Rinse a portion quickly for 'plain chicken' kids — it still tastes great.", "One cook, three different-looking dinners."],
    grownUp: "Use salsa verde or add chipotle." },
  { id: 'it-turkeyballs', name: "Baked Turkey & Spinach Meatballs", cuisine: 'italian', meal: 'Dinner', emoji: '🍝', time: 35, level: 'Easy', serves: 6,
    healthy: true, tags: ['hidden veg', 'freezer friendly', 'meal prep'], prep: { makes: '≈ 36 meatballs', keeps: '4 days fridge', freezer: '3 months', reheat: 'Simmer in sauce 10 min from frozen' },
    ingredients: ["700 g lean ground turkey", "1 cup frozen spinach, thawed and squeezed very dry, finely chopped", "1 egg", "½ cup breadcrumbs", "½ cup grated parmesan", "1 tsp garlic powder, 1 tsp Italian seasoning, ½ tsp salt", "Marinara and pasta to serve"],
    steps: ["Heat oven to 400°F (200°C); line a sheet pan.", "Mix everything gently; roll into 1-inch balls.", "Bake 15–18 min until 165°F (74°C).", "Serve with sauce and pasta, or in subs. Freeze extras on a tray, then bag."],
    picky: ["Spinach chopped very fine is just 'green flecks' — call them 'Hulk meatballs'.", "Serve with a dip cup of sauce instead of drowning them."],
    grownUp: "Add chili flakes and fresh basil; top with ricotta." },
];

const HEALTHY = ['ca-salmon', 'th-larb', 'cn-eggdrop', 'mx-bowl', 'mx-fajitas', 'cn-beefbroc', 'jp-teriyaki', 'it-hiddenveg', 'th-satay', 'us-tenders', 'th-freshrolls'];
const PREP = {
  'us-bbq': { makes: '8 sliders + leftovers', keeps: '4 days fridge', freezer: '3 months', reheat: 'Microwave with a splash of sauce' },
  'jp-curry': { makes: '6 bowls', keeps: '4 days fridge', freezer: '2 months (potatoes soften)', reheat: 'Stovetop, add water to loosen' },
  'it-meatballs': { makes: '≈ 40 mini meatballs', keeps: '4 days fridge', freezer: '3 months', reheat: 'Simmer in sauce from frozen 12 min' },
  'it-rollups': { makes: '12 roll-ups', keeps: '4 days fridge', freezer: '3 months (unbaked or baked)', reheat: '350°F covered 20–25 min' },
  'mx-breakfast': { makes: '6 burritos', keeps: '3 days fridge', freezer: '2 months', reheat: 'Microwave 1–2 min in a paper towel' },
  'ca-bites': { makes: '18 bites', keeps: '1 week fridge', freezer: '2 months' },
  'mx-bowl': { makes: '4–5 bowls', keeps: '4 days fridge', reheat: 'Microwave 2 min (add cold toppings after)' },
  'jp-teriyaki': { makes: '4–5 bowls', keeps: '4 days fridge', reheat: 'Microwave 2 min' },
  'ca-shepherd': { makes: '6 servings', keeps: '4 days fridge', freezer: '3 months', reheat: '350°F 25 min or microwave' },
  'it-hiddenveg': { makes: 'Sauce for 3 dinners', keeps: '5 days fridge', freezer: '3 months (sauce only)', reheat: 'Warm sauce, toss with fresh pasta' },
  'us-meatloaf': { makes: '12 mini loaves', keeps: '4 days fridge', freezer: '3 months', reheat: 'Microwave 1 min each' },
  'cn-dumplings': { makes: '40 dumplings', freezer: '3 months (freeze uncooked)', reheat: 'Cook from frozen, add 2 min steam' },
};
BASE.forEach(r => { if (HEALTHY.includes(r.id)) r.healthy = true; if (PREP[r.id]) r.prep = PREP[r.id]; });
export const RECIPES = [...BASE, ...MORE];
export const isPrep = r => !!r.prep;

// Deterministic daily picks: rotate through cuisines so the feed changes every day but is the same on every device.
export function dailyPicks(dateStr, count = 4, shuffle = 0) {
  const seed = [...(dateStr + (shuffle ? '#' + shuffle : ''))].reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, 7);
  const rand = mulberry(seed);
  const pool = RECIPES.filter(r => r.meal === 'Dinner' || r.meal === 'Lunch');
  const byCuisine = CUISINES.map(c => pool.filter(r => r.cuisine === c.id));
  const start = Math.floor(rand() * CUISINES.length);
  const picks = [];
  for (let i = 0; picks.length < count && i < CUISINES.length * 2; i++) {
    const list = byCuisine[(start + i * 2) % CUISINES.length];
    const r = list[Math.floor(rand() * list.length)];
    if (r && !picks.includes(r)) picks.push(r);
  }
  // one breakfast or snack bonus pick
  const extras = RECIPES.filter(r => r.meal === 'Breakfast' || r.meal === 'Snack');
  picks.push(extras[Math.floor(rand() * extras.length)]);
  return picks;
}

function mulberry(a) {
  return function () {
    a |= 0; a = a + 0x6D2B79F5 | 0;
    let t = Math.imul(a ^ a >>> 15, 1 | a);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
